// WARNING: this file contains profanity. The below list of profane words is necessary for this tool to function properly.
// Do not read below this line if you do not wish to be exposed to lots of profane words

module.exports = [
    "বোকাচোদা",
    "bokachoda",
    "bokachuda",
    "মাদৰচোদ",
    "madarchod",
    "madrchod",
    "ভেনচোদ",
    "bhenchod",
    "bhnchod",
    "venchod",
    "চুটি",
    "chuti",
    "chutii",
    "chutiya",
    "চুতীয়া",
    "chutia",
    "chutiyaa",
    "হৰামজাদা",
    "haramzada",
    "haraamjada",
    "hrmzda",
    "ৰাণ্ডী",
    "randi",
    "rundy",
    "raandi",
    "গাঁডু",
    "gandu",
    "gaandu",
    "লুণ্ড",
    "lund",
    "lond",
    "lunda",
    "চোদন",
    "chodon",
    "chudan",
    "জাৰ",
    "jaar",
    "jar",
    "তোৰ মাক চুদিম",
    "tor maak chudim",
    "tor maa ko ch*du",
    "তোৰ ভাইন চুদিম",
    "tor bhain chudim",
    "tor bhn chodu",
    "খং খোৱা বোকাচোদা",
    "khang khuwa bokachoda",
    "khang bokachod",
    "জোতখোৱা",
    "jotkhowa",
    "jotkhua",
    "jothkhua",
    "চালীৰ বাচা",
    "chali'r bacha",
    "chaalir bacha",
    "ch** ke bacche",
    "মাদারচোদ",
    "বেশ্যা",
    "beshya",
    "চুদাচুদি",
    "chudachudi",
    "চুদতে চাই",
    "chudte chai",
    "বাজে কথা",
    "baje kotha",
    "চুতমারানি",
    "chutmarani",
    "চোদনখোর",
    "chodonkhor",
    "চুদি",
    "chudi",
    "গান্ডু",
    "বালের কাজ",
    "barer kaj",
    "চু চু",
    "chu chu",
    "তোর মা চুদব",
    "tor ma chudbo",
    "তোর বোন চুদব",
    "tor bon chudbo",
    "চুদে ফেলবো",
    "chude felbo",
    "চুদ",
    "chud",
    "গাঁড় মারবো",
    "gand marbo",
    "রেন্ডি",
    "rendi",
    "চুদি মাগি",
    "chudi magi",
    "তুই একটা হারামজাদা",
    "tui ekta haramjada",
    "তুই কুত্তার বাচ্চা",
    "tui kuttar baccha",
    "চুদি বাল",
    "chudi baal",
    "হারামজাদা",
    "haramjada",
    "চুতিয়া",
    "চোদা",
    "choda",
    "বালের ছেলে",
    "barer chele",
    "চুদে দে",
    "chude de",
    "চুদে দিবি",
    "chude dibi",
    "চুদে নে",
    "chude ne",
    "চুদে খা",
    "chude kha",
    "চুদে ফেল",
    "chude fel",
    "बहनचो*",
    "behnchod",
    "मादरचो*",
    "mdrchd",
    "चुतिया",
    "भोसड़ी",
    "bhosadi",
    "bhosdi",
    "bhosdike",
    "लंड",
    "lnd",
    "गांडू",
    "रंडी",
    "rundi",
    "हरामी",
    "haraami",
    "harami",
    "चो*बे",
    "chodbe",
    "chod le",
    "चो*ल",
    "chodal",
    "तहार माई के",
    "tahar mai ke",
    "tohar mai ke",
    "तहार बहिन के",
    "tahar bahin ke",
    "tohar bahan ke",
    "गांड फाट जाई",
    "gand phat jai",
    "gaand phat jaayi",
    "गांड मरवले बाड़",
    "gand marwale bad",
    "gaand marwaye bda",
    "चुत मार",
    "chut maar",
    "chut mar",
    "झाड़ ले",
    "jhaad le",
    "jhad le",
    "भक चोद",
    "bhak chod",
    "bhaak chud",
    "भोसड़ी के",
    "bhosdi ke",
    "तू झटुआ ह",
    "tu jhatua hai",
    "tu jhatuwa h",
    "झट",
    "jhat",
    "jhaat",
    "लुड़ा",
    "luda",
    "luraa",
    "बिलंड",
    "bilund",
    "biland",
    "नाजायज औलाद",
    "najayaz aulad",
    "najayaj aulaad",
    "bhosari",
    "मादरचोद",
    "बहनचोद",
    "हरामजादा",
    "लुंड",
    "झांट",
    "तेरे बाप की...",
    "tere baap ki",
    "tere bap ki",
    "तेरी माई की...",
    "teri maai ki",
    "teri maa ki",
    "तेरी गांड मारूँ",
    "teri gaand maarun",
    "चूतिया",
    "हरामखोर",
    "haramkhor",
    "कुत्ते की औलाद",
    "kutte ki aulaad",
    "गांड फाड़ दूँ",
    "gaand fad du",
    "gand phaad doon",
    "bhosri ke",
    "chutya",
    "रांड़",
    "rand",
    "raand",
    "तेला चोद देहूँ",
    "tela chod dehu",
    "tela chod dunga",
    "तेर माई के...",
    "ter mai ke",
    "कुत्ते के पिल्ला",
    "kutte ke pilla",
    "kutte ka baccha",
    "ચુતિયા",
    "ભોસડીવો",
    "bhosdivo",
    "માદરચોદ",
    "બહેનચોદ",
    "behenchod",
    "લંડ",
    "ગાંડુ",
    "ભોસડી",
    "હરામી",
    "કમીનો",
    "kameeno",
    "ગાંડ મારીશ",
    "gaand marish",
    "તારું લેવું છે",
    "taru levu chhe",
    "તારિ બહેન",
    "taari behen",
    "તારિ માઁ",
    "taari maa",
    "ફટ્ટુ",
    "phattu",
    "ચોધવાઈ ગયેલો",
    "chodhvai gayelo",
    "ચુદાઈ કરે",
    "chudaai kare",
    "ચુતની જમાત",
    "chutni jamaat",
    "ભડવો",
    "bhadvo",
    "ભાડમાં જા",
    "bhaadma jaa",
    "ભણતર ન હોય",
    "bhanatar na hoy",
    "gndu",
    "hrmi",
    "hrmkhor",
    "रांड",
    "झाट",
    "jhatka",
    "भड़वा",
    "bhadwa",
    "bhadva",
    "bhaduwa",
    "बकलोल",
    "baklol",
    "bakloul",
    "खच्चर",
    "khacchar",
    "kchhr",
    "तेरी माँ की...",
    "teri ma ki",
    "तेरी बहन की...",
    "teri bahan ki",
    "teri behan ki",
    "तेरा बाप हूँ",
    "tera baap hoon",
    "tera bap hu",
    "teri gand marun",
    "भोसड़ी के छोरे",
    "bhosdi ke chore",
    "bhosdi ka chora",
    "गाली",
    "साला",
    "गांड",
    "भोसड़ीके",
    "कमीना",
    "कुत्ता",
    "झंड",
    "चूत",
    "चुतमाई",
    "भोसड़ीवाले",
    "साले",
    "चोतीया",
    "मादर",
    "चोद",
    "चु***",
    "भेंचोद",
    "तेरी मां की",
    "तेरी बहन की",
    "घांटिया",
    "नालायक",
    "फट्टू",
    "ढक्कन",
    "सुड़िया",
    "ठरकी",
    "कुतिया",
    "दल्ला",
    "चुतिया साला",
    "गांडू साला",
    "चूतड़",
    "चूतड़िया",
    "हरामी की औलाद",
    "हरामजादी",
    "मादरसा",
    "भड़वी",
    "चुचुंदर",
    "गांडू के बच्चे",
    "भोसड़ी की औलाद",
    "हरामी साला",
    "भड़वा साला",
    "रंडी का बच्चा",
    "भोसड़ी के बच्चे",
    "मादरचोद के बच्चे",
    "बहनचोद के बच्चे",
    "चूतिया के बच्चे",
    "हरामी के बच्चे",
    "चूतड़ के बच्चे",
    "भड़वी की औलाद",
    "हरामखोर साला",
    "भोसड़ीवाले के बच्चे",
    "हरामजादी की औलाद",
    "कुत्ते का पिल्ला",
    "रंडी की औलाद",
    "हरामी औरत",
    "भड़वा की औलाद",
    "मादरचोद साला",
    "बहनचोद साला",
    "गांडू की औलाद",
    "चूतिया औरत",
    "भोसड़ी की बच्ची",
    "रंडी की बच्ची",
    "हरामखोर की औलाद",
    "हरामी बच्चा",
    "मादरचोद की औलाद",
    "भड़वी साली",
    "ಗಾಂಡು",
    "ಸುನ್ದಿ",
    "sundi",
    "ಚೂತಿ",
    "chooti",
    "ಲೋಫರ್",
    "loafer",
    "ಕೂಲಿ ನಾಯಿ",
    "kooli naayi",
    "ನಾಯಿಮಗ",
    "naayi maga",
    "ಬೋಸುಡಿ",
    "bosudi",
    "ಬಂಡೆ",
    "bande",
    "ಗಂಡಾಚೋರ",
    "ganda chora",
    "ಚೆಡ್ಡವನ",
    "cheddavana",
    "ಮೂಢನ",
    "moodhana",
    "ಚುಚ್ಚುಮಗ",
    "chuchchu maga",
    "ತಿನ್ನೋ ನಾಯಿ",
    "thinnonaayi",
    "ನಿನ್ ಅಪ್ಪನ",
    "nin appana",
    "ಚಂದ್ರಮುಖಿ",
    "chandramukhi",
    "ಪೆದ್ದ",
    "pedda",
    "ಕುಡಿಗ",
    "kudiga",
    "ಕೂವತ್ತ",
    "koovatta",
    "ಬುದ್ಧಿಹೀನ",
    "buddhihiina",
    "ಜೋಕರ",
    "joker",
    "londa",
    "कुत्र्या चे पोरा",
    "kutrya che pora",
    "kutrya ka baccha",
    "तुझ्या मायचे",
    "tuzya mayche",
    "tuzya maa ke",
    "तोहर माई के...",
    "tohar maa ke",
    "तोहर भोसड़ी...",
    "tohar bhosdi",
    "tohar bhosdi ke",
    "कुत्ता के पिल्ला",
    "kutta ke pilla",
    "പോഡാ",
    "poda",
    "പൊന്നീ",
    "ponni",
    "തല്ലു വാങ്ങ്",
    "thallu vaang",
    "തെറ്റൻ",
    "thettan",
    "കുഴപ്പക്കാരൻ",
    "kuzhappakkaran",
    "പെണ്ണാട്ടൻ",
    "pennaattan",
    "മക്കളെ ഇല്ലാത്തവൻ",
    "makkale illathavan",
    "താരളന്‍",
    "thaaralan",
    "ചോദ്യക്കാരൻ",
    "chodyakkaran",
    "കള്ളൻ",
    "kallan",
    "നൈസ് നായ്",
    "nais naayi",
    "തവള",
    "thavala",
    "മണ്ടൻ",
    "mandan",
    "കുഴപ്പമുള്ളവൻ",
    "kuzhappam ullavan",
    "തരംതാഴ്ന്നവൻ",
    "tharam thazhnavan",
    "വള്ള്യ പണി",
    "valliya pani",
    "തല്ലാൻ പോകൂ",
    "thallaan poku",
    "പോവെട്ട",
    "povetta",
    "നിന്റെ അമ്മയെ...",
    "ninte ammaye...",
    "നിന്റെ ചേച്ചിയെ...",
    "ninte chechhiye...",
    "चुतीया",
    "भोसडी",
    "च्यायला",
    "chyaayla",
    "झटका",
    "jatka",
    "शेंडी",
    "shendi",
    "झटक्या",
    "jatkya",
    "भडवा",
    "बोसडीचा",
    "bosdicha",
    "झक मार",
    "jhakk maar",
    "झोपडीचा",
    "jhopdicha",
    "गांड मारू",
    "gaand maaru",
    "भोसडीचा",
    "bhosdicha",
    "कुत्र्याच्या पिल्ला",
    "kutryachya pilla",
    "तुझी आई",
    "tuzhi aai",
    "तुझी बहिन",
    "tuzhi bahin",
    "haraamkhor",
    "naalayak",
    "फाटलेला",
    "phatlela",
    "tharki",
    "chut",
    "chute",
    "chutiy",
    "gaand",
    "gand",
    "lundra",
    "कुत्तो",
    "kutto",
    "थारी माँ की...",
    "thari maa ki",
    "thari ma ki",
    "थारी बहन की...",
    "thari bahan ki",
    "thari behan ki",
    "थन चोद दूं",
    "than chod doon",
    "than ch*d doon",
    "हरामजादो",
    "haramjado",
    "haramjaada",
    "बकचोदी",
    "bakchodi",
    "bakchod",
    "भांड",
    "bhand",
    "bhaand",
    "थू चोद",
    "thoo chod",
    "thu chod",
    "ভোসড়ি",
    "bhosri",
    "চুতি",
    "লুন্ড",
    "হরামজাদা",
    "কুত্তার বাচ্চা",
    "kutta ka baccha",
    "ମାଗି",
    "magi",
    "ରଣ୍ଡୀ",
    "ଚୋଡ଼",
    "ମାଦରଚୋଦ",
    "ବହଞଚୋଦ",
    "ଗଣ୍ଡ",
    "ଚୁତିଆ",
    "ଭୋସଡ଼ି",
    "ଲଣ୍ଡ",
    "ହରାମୀ",
    "କୁକୁର ପିଲା",
    "kukur pila",
    "ଗୋଭିନ୍ଦ",
    "govinda",
    "ଧିକ୍କାର",
    "dhikkar",
    "ଗଂଧା",
    "gandha",
    "ମୁଁ ତୋ ମା' ଙ୍କୁ ଚୋଡ଼ିବି",
    "mu to maa ku chodibi",
    "ତୋ ଭଉଣୀ",
    "to bhauni",
    "ଚୋଡ଼ିବି",
    "chodibi",
    "ତୋର ଗାଣ",
    "tora gaan",
    "ଅପମାନଜନକ",
    "apamaanajanaka",
    "ବେଶ୍ୟା",
    "ਭੋਸੜੀਕੇ",
    "bhosrike",
    "ਚੂਤੀਆ",
    "chuteya",
    "ਮਾਦਰਚੋਦ",
    "ਭੈਣਚੋਦ",
    "ਰੰਡੀ",
    "ਕੰਜਰ",
    "kanjar",
    "kanjarr",
    "ਲੰਡ",
    "ਗਾਂਡੂ",
    "ਚੋਦੀ",
    "chodi",
    "ਝਾਟ",
    "ਕੁੱਤੇ",
    "kutte",
    "kutta",
    "ਤੱਤਿਆ",
    "tattiya",
    "tatya",
    "ਚੋਪਣ",
    "chopan",
    "chopun",
    "ਤੇਰੀ ਮਾਂ ਦੀ...",
    "teri maa di",
    "teri maa da",
    "ਤੇਰੀ ਭੈਣ ਦੀ...",
    "teri bhen di",
    "teri bahan di",
    "ਚਮਚੀ",
    "chamchi",
    "chamcha",
    "ਫੁਟਰੀ",
    "phutri",
    "phutree",
    "ਕੁਤੀਆ",
    "kutiya",
    "kuttiya",
    "kutti",
    "ਚੂਚੀ",
    "chuchi",
    "chuchiyan",
    "ਲੋੜੀ",
    "lodi",
    "lorry",
    "घणी मादर...",
    "ghani madarchod",
    "ghani maa ke",
    "तने चोद दूं",
    "tane chod doon",
    "tne ch*d doon",
    "thari bhn ki",
    "झणाण",
    "jhanana",
    "jhnaan",
    "jhanan",
    "மூடா",
    "mooda",
    "புன்னாக்கு",
    "punnakku",
    "தரமையாதவன்",
    "tharamaiyadaavan",
    "தரமையாதவள்",
    "tharamaiyadaaval",
    "பொம்பளைக்கேவளி",
    "pombalaikevali",
    "சூத்து",
    "soothu",
    "வாயப்புடி",
    "vaayappudi",
    "சட்டை கழடு",
    "sattai kazhadu",
    "பச்சி",
    "pachchi",
    "முட்டாள்",
    "muttaal",
    "தோழி புடுங்கி",
    "thozhi pudungi",
    "மயிரு",
    "mayiru",
    "தாயி ன பை",
    "thaayin pai",
    "பொறுக்கி",
    "porukki",
    "கூலி பண்டி",
    "kooli pundi",
    "தரமையா",
    "tharamaayaa",
    "வயிறு கிழியட்டும்",
    "vayiru kizhiattum",
    "நாயே",
    "naaye",
    "கொல்லட்டும்",
    "kollattum",
    "உன் மூத தாய்",
    "un mootha thaai",
    "దన్నా కొడుకా",
    "danna koduka",
    "నీకేమైనా దిమ్మ తిక్కా ఉంది",
    "neekemaina dimma thikka undi",
    "లంజ",
    "lanja",
    "లంజకుమారుడు",
    "lanja kumarudu",
    "దయ్యాల పిల్ల",
    "dayyala pilla",
    "గాండీ",
    "gaandi",
    "పొక్క",
    "pokka",
    "గాడిద",
    "gadida",
    "గోనుపల్లే",
    "gonupalle",
    "తల్లి దండ్రులను తిట్టడం",
    "thalli dandrulanu tittadam",
    "పోరా బద్దకస్తుడు",
    "pora baddakastudu",
    "నీ మావ",
    "nee maava",
    "బకరా",
    "bakara",
    "దారుణం",
    "daarunam",
    "గతిగా ఉంది నీ మెదడు",
    "gathiga undi nee medadu",
    "నీ ముద్దు పెట్టుకుందాం",
    "nee muddu pettukundam",
    "అశ్లీలంగా మాట్లాడకు",
    "ashleelanga matladaku",
    "వెక్కిరించడం",
    "vekkirinchadam",
    "తిన మండి",
    "thina mandi",
    "తిమ్మిరి",
    "thimmiri",
    "حرامی",
    "کمینہ",
    "kameena",
    "چوتیا",
    "ماں چود",
    "maan chod",
    "بہن چود",
    "behen chod",
    "گاندو",
    "لنڈ",
    "چدنے والا",
    "chadne wala",
    "بوسڑی کے",
    "کنجر",
    "رنڈی",
    "بھڑوا",
    "گشتی",
    "gashti",
    "چوتڑ",
    "chutar",
    "تیری ماں کی",
    "تم حرامی ہو",
    "tum haraami ho",
    "چوپ کر",
    "chup kar",
    "موٹا سور",
    "mota soor",
    "کتے کا بچہ",
    "kutte ka bacha",
    "حرام خور",
    "en",
    "4r5e",
    "5h1t",
    "5hit",
    "a55",
    "anal",
    "anus",
    "ar5e",
    "arrse",
    "arse",
    "arses",
    "ass",
    "ass-fucker",
    "asses",
    "assfucker",
    "assfukka",
    "asshole",
    "assholes",
    "asswhole",
    "a_s_s",
    "a$$",
    "as$",
    "a$s",
    "b!tch",
    "b00bs",
    "b17ch",
    "b1tch",
    "ballbag",
    "balls",
    "ballsack",
    "bastard",
    "beastial",
    "beastiality",
    "bellend",
    "bestial",
    "bestiality",
    "bi+ch",
    "biatch",
    "bitch",
    "bitchboy",
    "bitcher",
    "bitchers",
    "bitches",
    "bitchin",
    "bitching",
    "bloody",
    "blow job",
    "blowjob",
    "blowjobs",
    "boiolas",
    "bollock",
    "bollok",
    "boner",
    "boob",
    "boobs",
    "booobs",
    "boooobs",
    "booooobs",
    "booooooobs",
    "breasts",
    "buceta",
    "bugger",
    "bullshit",
    "bum",
    "butt",
    "butts",
    "butthole",
    "buttmuch",
    "buttplug",
    "c0ck",
    "c0cksucker",
    "carpet muncher",
    "cawk",
    "chink",
    "cipa",
    "cl1t",
    "clit",
    "clitoris",
    "clits",
    "cnut",
    "cock",
    "cock-sucker",
    "cockface",
    "cockhead",
    "cockmunch",
    "cockmuncher",
    "cocks",
    "cocksuck",
    "cocksucked",
    "cocksucker",
    "cocksucking",
    "cocksucks",
    "cocksuka",
    "cocksukka",
    "cok",
    "cokmuncher",
    "coksucka",
    "coon",
    "cox",
    "crap",
    "cum",
    "cummer",
    "cumming",
    "cums",
    "cumshot",
    "cunilingus",
    "cunillingus",
    "cunnilingus",
    "cunt",
    "cuntlick",
    "cuntlicker",
    "cuntlicking",
    "cunts",
    "cyalis",
    "cyberfuc",
    "cyberfuck",
    "cyberfucked",
    "cyberfucker",
    "cyberfuckers",
    "cyberfucking",
    "d1ck",
    "damn",
    "dick",
    "dickhead",
    "dildo",
    "dildos",
    "dink",
    "dinks",
    "dirsa",
    "dlck",
    "dog-fucker",
    "doggin",
    "dogging",
    "donkeyribber",
    "doosh",
    "duche",
    "dyke",
    "ejaculate",
    "ejaculated",
    "ejaculates",
    "ejaculating",
    "ejaculatings",
    "ejaculation",
    "ejakulate",
    "f u c k",
    "f u c k e r",
    "f4nny",
    "fag",
    "fagging",
    "faggitt",
    "faggot",
    "faggs",
    "fagot",
    "fagots",
    "fags",
    "fanny",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fatass",
    "fcuk",
    "fcuker",
    "fcuking",
    "feck",
    "fecker",
    "felching",
    "fellate",
    "fellatio",
    "fingerfuck",
    "fingerfucked",
    "fingerfucker",
    "fingerfuckers",
    "fingerfucking",
    "fingerfucks",
    "fistfuck",
    "fistfucked",
    "fistfucker",
    "fistfuckers",
    "fistfucking",
    "fistfuckings",
    "fistfucks",
    "flange",
    "fook",
    "fooker",
    "fuck",
    "fucka",
    "fucked",
    "fucker",
    "fuckers",
    "fuckhead",
    "fuckheads",
    "fuckin",
    "fucking",
    "fuckings",
    "fuckingshitmotherfucker",
    "fuckme",
    "fucks",
    "fuckwhit",
    "fuckwit",
    "fudge packer",
    "fudgepacker",
    "fuk",
    "fuker",
    "fukker",
    "fukkin",
    "fuks",
    "fukwhit",
    "fukwit",
    "fux",
    "fux0r",
    "f_u_c_k",
    "gangbang",
    "gangbanged",
    "gangbangs",
    "gaylord",
    "gaysex",
    "goatse",
    "god-dam",
    "god-damned",
    "goddamn",
    "goddamned",
    "hardcoresex",
    "headass",
    "hoar",
    "hoare",
    "hoer",
    "hoes",
    "homo",
    "hore",
    "horniest",
    "horny",
    "hotsex",
    "jack-off",
    "jackoff",
    "jap",
    "jerk-off",
    "jism",
    "jiz",
    "jizm",
    "jizz",
    "kawk",
    "knobead",
    "knobed",
    "knobend",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "kock",
    "kondum",
    "kondums",
    "kum",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "l3i+ch",
    "l3itch",
    "labia",
    "lust",
    "lusting",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "masochist",
    "master-bate",
    "masterb8",
    "masterbat*",
    "masterbat3",
    "masterbate",
    "masterbation",
    "masterbations",
    "masturbate",
    "mo-fo",
    "mof0",
    "mofo",
    "mothafuck",
    "mothafucka",
    "mothafuckas",
    "mothafuckaz",
    "mothafucked",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking",
    "mothafuckings",
    "mothafucks",
    "motherfuck",
    "motherfucked",
    "motherfucker",
    "motherfuckers",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherfuckka",
    "motherfucks",
    "muff",
    "muthafecker",
    "muthafuckker",
    "mutherfucker",
    "n1gga",
    "n1gger",
    "nazi",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggas",
    "niggaz",
    "nigger",
    "niggers",
    "nob",
    "nob jokey",
    "nobhead",
    "nobjocky",
    "nobjokey",
    "numbnuts",
    "nutsack",
    "orgasim",
    "orgasims",
    "orgasm",
    "orgasms",
    "p0rn",
    "pawn",
    "pecker",
    "penis",
    "penisfucker",
    "phonesex",
    "phuck",
    "phuk",
    "phuked",
    "phuking",
    "phukked",
    "phukking",
    "phuks",
    "phuq",
    "pigfucker",
    "pimpis",
    "piss",
    "pissed",
    "pisser",
    "pissers",
    "pisses",
    "pissflaps",
    "pissin",
    "pissing",
    "pissoff",
    "poop",
    "porn",
    "porno",
    "pornography",
    "pornos",
    "prick",
    "pricks",
    "pron",
    "pube",
    "pusse",
    "pussi",
    "pussies",
    "pussy",
    "pussys",
    "rectum",
    "retard",
    "rimjaw",
    "rimming",
    "s hit",
    "s.o.b.",
    "sadist",
    "schlong",
    "screwing",
    "scroat",
    "scrote",
    "scrotum",
    "semen",
    "sex",
    "sh!+",
    "sh!t",
    "sh1t",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "shemale",
    "shi+",
    "shit",
    "shitdick",
    "shite",
    "shited",
    "shitey",
    "shitfuck",
    "shitfull",
    "shithead",
    "shiting",
    "shitings",
    "shits",
    "shitted",
    "shitter",
    "shitters",
    "shitting",
    "shittings",
    "shitty",
    "skank",
    "slut",
    "sluts",
    "smegma",
    "smut",
    "snatch",
    "son-of-a-bitch",
    "spac",
    "spunk",
    "s_h_i_t",
    "t1tt1e5",
    "t1tties",
    "teets",
    "teez",
    "testical",
    "testicle",
    "tit",
    "titfuck",
    "tits",
    "titt",
    "tittie5",
    "tittiefucker",
    "titties",
    "tittyfuck",
    "tittywank",
    "titwank",
    "tosser",
    "turd",
    "tw4t",
    "twat",
    "twathead",
    "twatty",
    "twunt",
    "twunter",
    "v14gra",
    "v1gra",
    "vagina",
    "viagra",
    "vulva",
    "w00se",
    "wang",
    "wank",
    "wanker",
    "wanky",
    "whoar",
    "whore",
    "willies",
    "willy",
    "الحصان",
    "المؤخرات",
    "مؤخرة",
    "الوغد",
    "الحمير",
    "أحمق",
    "حمقى",
    "الأحمق",
    "دولار",
    "كدولارات",
    "(ب)",
    "الكرة",
    "الكرات",
    "كرات",
    "الوحشية",
    "الجرس",
    "الأفضلية",
    "b+ch",
    "الكلبة",
    "الكلبات",
    "العاهرات",
    "اللعنة",
    "عمل فاسد",
    "أعمال تفجيرية",
    "هراء",
    "العظام",
    "صدر",
    "الثدي",
    "البوق",
    "عصيان",
    "البوووب",
    "حشرة",
    "مقهى",
    "قضيب",
    "وغد",
    "وجهك",
    "القضيب",
    "كوكر",
    "أيها الوغد",
    "سحقًا",
    "صراخ",
    "كوك",
    "كوكاكوتا",
    "كوكس",
    "حثالة",
    "الطهي",
    "النقر",
    "العبث",
    "الحمقى",
    "الإنترنت(ج)",
    "الفضاء الإلكتروني",
    "الملاعين السيبرانيين",
    "تسلل عبر الإنترنت",
    "دينك",
    "♪",
    "الكلب اللعين",
    "الكلب",
    "حبوب منع الحمل",
    "الإيجاز",
    "الجزيئات",
    "الهرجات",
    "القذف",
    "زائفة",
    "الشاذ",
    "الشواذ",
    "الكلاب",
    "فاني",
    "الملاعين",
    "الخيال",
    "الدهون",
    "متعهد",
    "الحضانات",
    "فاسد",
    "المهرجان",
    "سقط",
    "قبضة لعينة",
    "مارس الجنس مع",
    "اللعين",
    "سخيف",
    "أيها اللعين",
    "حمأة",
    "فوك",
    "فوكر",
    "صمامات",
    "فوكوهي",
    "فوكويت",
    "الثعلب",
    "العصابات",
    "مثلي الجنس",
    "الماعز",
    "يا إلهي",
    "صلبة",
    "الرأس",
    "الأشقر",
    "مثارة",
    "مثير",
    "(جاك أوف)",
    "(جاك)",
    "حبس",
    "الكوندوم",
    "الكم",
    "المختبرات",
    "شهوة",
    "الإغراء",
    "m0f",
    "الماجستير",
    "مسوخ",
    "درجة الماجستير",
    "الماجستير(ب)",
    "المناقشة العامة*",
    "المناقشة الرئيسية 3",
    "سيدي",
    "التحفة",
    "الاستمناء",
    "موثا",
    "مضاجعة",
    "الأوغاد",
    "لعين",
    "ملاعين",
    "نازي",
    "زنجي",
    "الزنوج",
    "نابوكي",
    "الراهبات",
    "مجنون",
    "النشوة",
    "الأورام",
    "الرهن",
    "بيكر",
    "الهواتف الجنسية",
    "رشاش",
    "رهبان",
    "الفوكة",
    "القواد",
    "بول",
    "سكران غاضب",
    "البول",
    "تبول",
    "المواد الإباحية",
    "الخوخ",
    "حانة",
    "نقية",
    "الجبناء",
    "جبان",
    "إعادة التشكيل",
    "المتخلفون",
    "قذف",
    "سادي",
    "الجنس",
    "ش",
    "شجر",
    "القرف",
    "عاهرة",
    "عاهرات",
    "ابن العاهرة",
    "سافل",
    "اختباري",
    "خصية",
    "أيها الحقير",
    "toser",
    "توان",
    "وانغ",
    "الويلات",
    "ويلي",
    "de",
    "arsch",
    "arschficker",
    "esel",
    "arschloch",
    "arschlöcher",
    "arschganz",
    "in %",
    "b.tch",
    "kugelbeutel",
    "eier",
    "bälle",
    "beastialität",
    "glocke",
    "bestialität",
    "schlampe",
    "hündchen",
    "metzger",
    "schlampen",
    "verdammt",
    "blasen",
    "knochen",
    "titten",
    "brüste",
    "buhn",
    "boooooobs",
    "fehler",
    "schwachsinn",
    "hintern",
    "kacke",
    "klitoris",
    "schwanz",
    "schwanzsauger",
    "schwanzkopf",
    "schwanzlutscher",
    "hahnmacher",
    "schwänze",
    "kokos",
    "kokmuncher",
    "koksucka",
    "mist",
    "kümmel",
    "fotze",
    "stiche",
    "cyberfickt",
    "cyberficker",
    "cyberficken",
    "hundeficker",
    "hunde",
    "eselibber",
    "ejakulat",
    "ejakuliert",
    "ejakulation",
    "schwuchtel",
    "schwuchteln",
    "phantasievoll",
    "fettass",
    "flat",
    "fingerfick",
    "fingerfickt",
    "fingerficker",
    "fingerficken",
    "fistfickt",
    "fistficken",
    "scheiße",
    "flansch",
    "fick",
    "gefickt",
    "wichser",
    "scheißkerle",
    "scheißkerl",
    "fick mich",
    "ficks",
    "fokkin",
    "ziegen",
    "gott-dam",
    "hor",
    "huhn",
    "geil",
    "ausleger",
    "knüppel",
    "idiot",
    "jisma",
    "knospead",
    "geknallt",
    "knaufende",
    "knopfkopf",
    "knospen",
    "knowjokey",
    "lustig",
    "m45terbat",
    "ma5terbat",
    "masterbat",
    "masterbationen",
    "masturbieren",
    "mottafucked",
    "verfickt",
    "nüsse",
    "nussack",
    "orgasime",
    "orgasmus",
    "orgasmen",
    "pfoten",
    "telefonsex",
    "schweinefucker",
    "pisse",
    "pissen",
    "pisseff",
    "pornografie",
    "muschis",
    "muschi",
    "rektum",
    "verzögert",
    "felgen",
    "schrauben",
    "skroat",
    "skrote",
    "skrotum",
    "samen",
    "geschlecht",
    "transen",
    "schlitten",
    "scheißkopf",
    "splitter",
    "scherben",
    "shank",
    "hoden",
    "dord",
    "wahnsinn",
    "hure",
    "es",
    "aus",
    "culo",
    "culos",
    "culo de mierda",
    "idiota",
    "imbécil",
    "idiotas",
    "culo completo",
    "a dólares",
    "a)",
    "bolsa de bolas",
    "bolas",
    "bastardo",
    "bestia",
    "bestialidad",
    "perra",
    "puta",
    "putas",
    "perras",
    "¡maldita sea",
    "mamada",
    "mamadas",
    "hueso",
    "tetas",
    "senos",
    "negro",
    "mierda",
    "entendido",
    "clítoris",
    "polla",
    "polla-sucker",
    "masturbación",
    "pene",
    "gallos",
    "pollas",
    "polla grande",
    "pollasucked",
    "chupavergas",
    "chupa pollas",
    "penes negros grandes",
    "colibrí",
    "corrida",
    "cuñada",
    "cuñas",
    "ciberpolvo",
    "cibernético",
    "¡mierda",
    "los ciberdelincuentes",
    "ciberdelincuente",
    "maldita sea",
    "consoladores",
    "perro mierda",
    "perro",
    "eyaculado",
    "eyaculada",
    "eyaculados",
    "eyaculando",
    "eyaculaciones",
    "eyaculación",
    "eyakulate",
    "maricón",
    "maricas",
    "faggit",
    "grasa",
    "fcuting",
    "caído",
    "♪♪",
    "dedo",
    "¡dedo",
    "dedos de mierda",
    "dedo de mierda",
    "dedos",
    "brida",
    "follada",
    "hijo de puta",
    "mierdas",
    "puta mierda",
    "mierda mierda mierda madre mierda mierda mierda",
    "maldición",
    "fusibles",
    "cabra",
    "maldito",
    "más caliente",
    "caliente",
    "kno",
    "lujuria",
    "masoquista",
    "bigotes",
    "hijos de puta",
    "madre mierda",
    "negros",
    "nueces",
    "orgasmo",
    "orgasmos",
    "peón",
    "chupa penes",
    "teléfonosex",
    "cabrón",
    "chulos",
    "orinar",
    "enojada",
    "meandos",
    "meadas",
    "pispa",
    "orina",
    "meando",
    "pornografía",
    "vaginas",
    "recto",
    "retardado",
    "sadista",
    "tornillo",
    "escroto",
    "sexo",
    "sh",
    "temblando",
    "transexual",
    "sunk",
    "t1t1e5",
    "testículo",
    "titular",
    "tittie",
    "fr",
    "5 heures",
    "arrs",
    "cul",
    "ânes",
    "enculé de cul",
    "culs",
    "enfoiré",
    "trou du cul",
    "gros cul",
    "a$",
    "en dollars",
    "c'est ça",
    "sac à bille",
    "boules",
    "sac à billes",
    "bâtard",
    "bête",
    "bêteté",
    "clocher",
    "bestialité",
    "salope",
    "les salopes",
    "salopes",
    "sanglant",
    "pipe",
    "pipes",
    "cliquetis",
    "osseux",
    "sein",
    "seins",
    "bouchons",
    "les nichons",
    "boucliers",
    "poitrines",
    "enculé",
    "des conneries",
    "fesses",
    "mégots",
    "gros plan",
    "plug anal",
    "chine",
    "clito",
    "nut",
    "coq",
    "suceur de bite",
    "visage de coq",
    "tête de coq",
    "munche de coq",
    "coq-muncher",
    "coqs",
    "sucre de bite",
    "bites sucées",
    "coqsucks",
    "sperme",
    "pomme",
    "spermes",
    "éjaculation",
    "pâte",
    "lèche-cul",
    "chattes",
    "les cyber-fuckers",
    "cyberdépannage",
    "putain",
    "bite",
    "tête de bite",
    "gode",
    "godes",
    "évier",
    "éviers",
    "enculé de chien",
    "chienne",
    "levrette",
    "d'ânes",
    "doux",
    "duché",
    "éjaculations",
    "éjaculate",
    "pour",
    "pédé",
    "signalisation",
    "foggitt",
    "peaux",
    "pédés",
    "les fannyflaps",
    "fany",
    "gras",
    "feu",
    "feuillage",
    "infesté",
    "taux de chute",
    "culotte",
    "avec les doigts",
    "enfoirés",
    "fucking des doigts",
    "bouchées de doigts",
    "farcis",
    "frappe de poing",
    "frappes de poing",
    "fusils",
    "bride",
    "merde",
    "baisée",
    "enculés",
    "espèce d'enfoiré",
    "crétins",
    "putains",
    "fils de pute",
    "baise-moi",
    "connard",
    "fox0r",
    "un gangbang",
    "bandes",
    "des gangs",
    "gaysexe",
    "caprins",
    "seigneur",
    "dieu maudit",
    "nom de dieu",
    "hardcoresexe",
    "tête de cul",
    "arnaque",
    "attaque",
    "sabots",
    "thorax",
    "les plus excités",
    "excité",
    "sexe chaud",
    "décollage",
    "branleur",
    "le jisme",
    "boutons",
    "boutonné",
    "bouton",
    "tête de bouton",
    "jocky",
    "boutonjokey",
    "le kumming",
    "des kums",
    "3 points",
    "luxure",
    "lustre",
    "m5terb8",
    "masochiste",
    "maître-bateau",
    "maîtreb8",
    "maître-bat*",
    "maîtrise3",
    "maître",
    "masturbe",
    "les",
    "merdeux",
    "le muthafecker",
    "4 h",
    "negga",
    "niggué",
    "nègre",
    "nègres",
    "tête de noeud",
    "engourdissements",
    "sac à noix",
    "orgasme",
    "orgasmes",
    "sur gage",
    "pic",
    "pénis",
    "suceur de pénis",
    "téléphonex",
    "purée",
    "ouvrés",
    "le phuking",
    "ouvrage",
    "les phuks",
    "maquereau",
    "en colère",
    "les pisseurs",
    "pousses de pisse",
    "caca",
    "pornographie mettant en scène des enfants",
    "pique",
    "les briques",
    "tablier",
    "pousse",
    "chatte",
    "jante",
    "sadique",
    "vissage",
    "scrotte",
    "sexe",
    "- oui",
    "s'il vous plaît",
    "sciages",
    "transexuelle",
    "merdique",
    "crétin",
    "des merdes",
    "sankk",
    "croûte",
    "t1tiétés",
    "tétons",
    "et toi",
    "testique",
    "testicule",
    "titre",
    "titre5",
    "lancer",
    "tuyau",
    "détecteur",
    "vagin",
    "vulve",
    "gland",
    "branlé",
    "souris",
    "pute",
    "walies",
    "it",
    "allupato",
    "ammucchiata",
    "anale",
    "arrapato",
    "arrusa",
    "arruso",
    "assatanato",
    "bagascia",
    "bagassa",
    "bagnarsi",
    "baldracca",
    "balle",
    "battere",
    "battona",
    "belino",
    "biga",
    "bocchinara",
    "bocchino",
    "bofilo",
    "boiata",
    "bordello",
    "brinca",
    "bucaiolo",
    "budiùlo",
    "busone",
    "cacca",
    "caciocappella",
    "cadavere",
    "cagare",
    "cagata",
    "cagna",
    "casci",
    "cazzata",
    "cazzimma",
    "cazzo",
    "cesso",
    "cazzone",
    "checca",
    "chiappa",
    "chiavare",
    "chiavata",
    "ciospo",
    "ciucciami il cazzo",
    "coglione",
    "coglioni",
    "cornuto",
    "cozza",
    "culattina",
    "culattone",
    "ditalino",
    "fava",
    "femminuccia",
    "fica",
    "figa",
    "figlio di buona donna",
    "figlio di puttana",
    "figone",
    "finocchio",
    "fottere",
    "fottersi",
    "fracicone",
    "fregna",
    "frocio",
    "froscio",
    "goldone",
    "guardone",
    "imbecille",
    "incazzarsi",
    "incoglionirsi",
    "ingoio",
    "leccaculo",
    "lecchino",
    "lofare",
    "loffa",
    "loffare",
    "mannaggia",
    "merda",
    "merdata",
    "merdoso",
    "mignotta",
    "minchia",
    "minchione",
    "mona",
    "monta",
    "montare",
    "mussa",
    "nave scuola",
    "nerchia",
    "padulo",
    "palle",
    "palloso",
    "patacca",
    "patonza",
    "pecorina",
    "pesce",
    "picio",
    "pincare",
    "pippa",
    "pinnolone",
    "pipì",
    "pippone",
    "pirla",
    "pisciare",
    "piscio",
    "pisello",
    "pistolotto",
    "pomiciare",
    "pompa",
    "pompino",
    "porca",
    "porca madonna",
    "porca miseria",
    "porca puttana",
    "porco",
    "porco due",
    "porco zio",
    "potta",
    "puppami",
    "puttana",
    "quaglia",
    "recchione",
    "regina",
    "rincoglionire",
    "rizzarsi",
    "rompiballe",
    "rompipalle",
    "ruffiano",
    "sbattere",
    "sbattersi",
    "sborra",
    "sborrata",
    "sborrone",
    "sbrodolata",
    "scopare",
    "scopata",
    "scorreggiare",
    "sega",
    "slinguare",
    "slinguata",
    "smandrappata",
    "soccia",
    "socmel",
    "sorca",
    "spagnola",
    "spompinare",
    "sticchio",
    "stronza",
    "stronzata",
    "stronzo",
    "succhiami",
    "succhione",
    "sveltina",
    "sverginare",
    "tarzanello",
    "terrone",
    "testa di cazzo",
    "tette",
    "tirare",
    "topa",
    "troia",
    "trombare",
    "vacca",
    "vaffanculo",
    "vangare",
    "zinne",
    "zio cantante",
    "zoccola",
    "hi",
    "गुदामैथुन",
    "एनस",
    "आर्सेना",
    "शस्त्र",
    "$$",
    "$",
    "b",
    "b00b",
    "बॉलबैग",
    "गेंद",
    "गेंदों",
    "बस्टर्ड",
    "जानवर",
    "समानता",
    "घंटी",
    "श्रेष्ठ",
    "श्रेष्ठता",
    "बिच",
    "बिटच",
    "चूंचियां",
    "बिटचर",
    "बिट्च",
    "बिटचिन",
    "बिटिंग",
    "खूनी",
    "बियोला",
    "बोल्क",
    "बोललोक",
    "हड्डी",
    "शराब",
    "स्तन",
    "बगीचा",
    "हिन्दी",
    "बट",
    "बटहोल",
    "बटमच",
    "चिंक",
    "क्लिट",
    "क्लिटोरिस",
    "अखरोट",
    "मुर्गा",
    "मुर्गा चूसने वाला",
    "कॉकफेस",
    "कॉक",
    "मुर्गा चूसने",
    "कोक",
    "कोन",
    "केकड़ा",
    "सह",
    "कमशॉट",
    "गुलगुला",
    "हिंदी",
    "चाचा",
    "साइबरफ़ुक",
    "साइबर बकवास",
    "डिक",
    "डिल्डो",
    "गुत्थी",
    "डंक",
    "कुत्ते-fucker",
    "कुत्ते",
    "गधा",
    "डोष",
    "डच",
    "डाइक",
    "ejaculations",
    "फ़ैग",
    "छूत",
    "चुभोना",
    "फैनी",
    "फैनीफ्लैप",
    "कट्टर",
    "वसा",
    "गिरना",
    "गिरती",
    "उंगली करना",
    "उंगलियों",
    "मुट्ठीकरना",
    "फुहार",
    "चॉकर",
    "भाड़ में जाओ",
    "बकवास",
    "गड़बड़",
    "मुख-मैथुन",
    "कमबख्त",
    "फक",
    "फूहड़",
    "गिरोह बैंग",
    "समलैंगिक",
    "बकरी",
    "देवता",
    "देवी",
    "कट्टरसेक्स",
    "सिर",
    "होर",
    "हो",
    "होम",
    "सींग का",
    "सेक्सी",
    "जैक ऑफ",
    "जैकपॉट",
    "जैप",
    "मरोड़ते",
    "जिज़",
    "जिज़्म",
    "कावा",
    "घुंडी",
    "कोंडोम",
    "कोन्डम",
    "कुम्भ",
    "गुनगुना",
    "लैबिया",
    "चमकना",
    "मैसोचिस्ट",
    "मास्टर-बेट",
    "मास्टरब8",
    "मास्टरबैट*",
    "मास्टरबैट3",
    "मास्टरबेट",
    "हस्तमैथुन",
    "साइटमैप",
    "माँ",
    "माताओं",
    "माफ",
    "नाज़ी",
    "निगा",
    "निगाह",
    "नागा",
    "नोब",
    "नोबहेड",
    "नट्सैक",
    "संभोग सुख",
    "p0",
    "मोहन",
    "पेकर",
    "पेनिस",
    "फोनसेक्स",
    "चक",
    "फुक",
    "फुकेत",
    "पिम्पिस",
    "पेशाब",
    "पेशाब करना",
    "पोप",
    "अश्लील",
    "पोर्नोग्राफी",
    "ट्रिक",
    "प्रोन",
    "पुसी",
    "बिल्ली",
    "राशि",
    "मंदिर",
    "रिमजॉ",
    "पेंच",
    "झरना",
    "घूंघट",
    "अंडकोष",
    "वीर्य",
    "सेक्स",
    "शि +",
    "shitful",
    "शिटिंग",
    "पतला",
    "शिथिल",
    "शिटर",
    "शिट्टी",
    "गुदगुदी",
    "छीनना",
    "बेटा",
    "स्पेक",
    "टट्टू",
    "टी1टी",
    "टी",
    "टीज़",
    "वृषण",
    "तैसा",
    "टिट्स",
    "टिट",
    "ट्वंट",
    "ट्वंटर",
    "योनि",
    "वियाग्रा",
    "वांग",
    "इच्छा",
    "ja",
    "4r5eの",
    "5ヒット",
    "の55",
    "アナル",
    "ログイン",
    "ar5eの",
    "アルス",
    "トピックス",
    "ass fucker",
    "アコース",
    "アスフッカ",
    "アスホール",
    "$$$$",
    "アスドル",
    "b!パッチ",
    "b00bsの",
    "b17chの",
    "b1tchの",
    "ボールバッグ",
    "ボールボール",
    "ボールバック",
    "バスタード",
    "ビーストリアル",
    "獣性",
    "ベルン",
    "ベスト",
    "人気カテゴリー",
    "bi+chの",
    "バイアッチ",
    "ビットチェボーイ",
    "ビットチャー",
    "ビットチャーズ",
    "ビットチェス",
    "ビットキャッシュ",
    "ブロージョブ",
    "ボヨラス",
    "ボルロック",
    "ボロク",
    "ボブ",
    "ブーブ",
    "ブーブス",
    "ブーツ",
    "ブームーブ",
    "ブームーブス",
    "ブラストス",
    "ボセタ",
    "バッガー",
    "ブルシット",
    "バム",
    "バッツ",
    "バトール",
    "バッチュ",
    "パスワード",
    "c0cksuckerの",
    "チンク",
    "プリカ",
    "クラス1t",
    "クライストリ",
    "クルミ",
    "コック",
    "コックサッカー",
    "コックフェイス",
    "コックヘッド",
    "コックムンチャー",
    "コックサック",
    "コック吸う",
    "コックキャッキング",
    "コックスカ",
    "コックスッカ",
    "コクンチャー",
    "コクサッカ",
    "コックス",
    "クムマー",
    "つぶやき",
    "カムス",
    "シアリス",
    "サイバーフック",
    "サイバーfuck",
    "サイバーfucked",
    "サイバーファッカー",
    "サイバーファッキング",
    "d1ckの",
    "ダムン",
    "dickheadの",
    "ディルドー",
    "ディルドス",
    "ダイニング",
    "ディルサ",
    "ダック",
    "犬 fucker",
    "ドッグギン",
    "ドッギング",
    "ドオッシュ",
    "デュチェ",
    "ダイケ",
    "エジャキュレート",
    "ejaculated(エジャキュレーション)",
    "電子メール",
    "ejaculating(エジャカルト)",
    "ejaculating(エジャキュレーション)",
    "ejakulateの",
    "おばあさん",
    "ファグ",
    "ファッギング",
    "ファゴット",
    "ファグス",
    "ファンニー",
    "ファンニーフラップ",
    "ファンニーfucker",
    "脂肪マッサージ",
    "フォーク",
    "フィードバック",
    "フェッカー",
    "落ち着き",
    "フィンガーfuck",
    "指fucked",
    "フィンガーファイヤー",
    "フィンガーファッカー",
    "指fucking",
    "フィンガーfucks",
    "フィストfuck",
    "フィストfuckers",
    "フランジ",
    "フーカー",
    "クソ",
    "フラッシャー",
    "クソヘッド",
    "fuckwhitさん",
    "fuckwitの",
    "ファッジパック",
    "フューカー",
    "フクカー",
    "フクキン",
    "ファクシミリ",
    "fukwitの",
    "ギャングバン",
    "ギャング",
    "ギャングバング",
    "ガールフレンド",
    "ゲイsexsex",
    "ヤギ",
    "ゴッドダム",
    "神秘的な被害を受けた",
    "ゴダメン",
    "ハードコアsexsex",
    "ヘッドサス",
    "ふりがな",
    "ホーンシーズ",
    "ホーンシー",
    "ホットsex",
    "ジャックオフ",
    "ジャークオフ",
    "ジャーミー",
    "カウク",
    "ノビーズ",
    "ノベット",
    "ノベンド",
    "ノブヘッド",
    "ノブジョキー",
    "コンドム",
    "コンダム",
    "クマー",
    "クムス",
    "l3i+chの",
    "l3itchの",
    "ラボリア",
    "プロフィール",
    "m0foの",
    "m45terbateの",
    "マ5terb8",
    "ma5terbateの",
    "マゾキスト",
    "マスター・リベート",
    "マスターb8",
    "マスターバット*",
    "マスターバット3",
    "マスターリベート",
    "マスタービング",
    "マスターブレーション",
    "モフォ",
    "モフ0",
    "モタクソファ",
    "モタクソファー",
    "母fuck",
    "母fucked",
    "母fucker",
    "母fuckers",
    "母fuckin",
    "母fucking",
    "母fuckings",
    "母fuckka",
    "母fucks",
    "マフ",
    "n1ggaの",
    "n1ガー",
    "ナジ",
    "ニグ3r",
    "ニグ4h",
    "ニグガ",
    "ナイガス",
    "ニガー",
    "ノブ",
    "ノブジョーキー",
    "ナムナッツ",
    "ナッツマック",
    "オーガスム",
    "オルガスム",
    "p0rnの",
    "プーン",
    "ペッカー",
    "ペニス",
    "電話sex",
    "ファック",
    "フクウク",
    "フィッシング",
    "ピッキング",
    "プーク",
    "ピクチャー",
    "ピンピス",
    "小便",
    "放尿",
    "小便小便",
    "プッシー",
    "ポップ",
    "恋物癖",
    "パトリック",
    "プロン",
    "パブ",
    "パッシー",
    "パスシス",
    "リクルート",
    "リタード",
    "リムジャウ",
    "リミング",
    "サディスト",
    "シュロン",
    "スクリュー",
    "セメン",
    "性別",
    "お問い合わせ",
    "ツイート",
    "sh1tの",
    "シェーグ",
    "シャガール",
    "シャギン",
    "シェーディング",
    "シーメール",
    "シープラス",
    "サイトマップ",
    "インタビュー",
    "シッター",
    "インフォメーション",
    "スカンク",
    "ソリューション",
    "スメグマ",
    "スムート",
    "スナッチ",
    "息子-of-a-bitch",
    "スパク",
    "t1tt1e5の特長",
    "t1タイ",
    "テッツ",
    "テエズ",
    "リファレンス",
    "アクティシクル",
    "タイ5",
    "ティワンク",
    "titwankの",
    "トッサー",
    "タード",
    "tw4tの",
    "タワトヘッド",
    "トワット",
    "トウランター",
    "v14graの",
    "v1graの",
    "バギーナ",
    "ビアグラ",
    "ワンク",
    "ワンカー",
    "ワンキー",
    "スタッフ",
    "パーティー",
    "メニュー",
    "ko",
    "4r5e를",
    "1시간",
    "5열",
    "a55's 수",
    "뚱 베어",
    "한국어",
    "사이트맵",
    "카테고리",
    "장바구니",
    "₢ 킹",
    "회사 소개",
    "제품 정보",
    "볼랙",
    "배틀그라운드",
    "제품정보",
    "채용 정보",
    "인기있는",
    "채용정보",
    "스낵 바",
    "뼈",
    "프로젝트",
    "바퀴 슈커",
    "큰 가슴",
    "채용공고",
    "인기 카테고리",
    "cyalis의",
    "사이버후크",
    "사이버감사",
    "사이버fucker",
    "사이버fuckers",
    "이름 *",
    "언어: 한국어",
    "개 게이",
    "개진",
    "관련 기사",
    "팟캐스트",
    "모든 새",
    "뚱뚱뚱",
    "· fcuk",
    "털이 많은",
    "주먹질",
    "중년부인",
    "옵션 정보",
    "빌어 먹을hitmotherfucker",
    "펌웨어",
    "갱뱅",
    "게이주",
    "게이sex",
    "신담",
    "뉴스 레터",
    "신담n",
    "하드코어sex",
    "맨 위로",
    "가장 핫한",
    "핫 성별",
    "잭 오프",
    "잭오프",
    "주 메뉴",
    "칼 머리",
    "칼조키",
    "엄마5terb8",
    "마스터베이트",
    "마스터b8",
    "마스터 배트*",
    "마스터배트3",
    "모thafuck",
    "모thafucka",
    "모thafuckas",
    "모thafuckaz",
    "모thafucked",
    "모thafucker",
    "모thafuckers",
    "모thafuckin",
    "모thafucking",
    "모thafucks",
    "엄마",
    "엄마fuckka",
    "모든 인기있는",
    "노브",
    "노브조키",
    "메뉴 닫기",
    "견과류",
    "오르가즘",
    "페커",
    "페니스",
    "오줌싸기",
    "pussys 소개",
    "핥기",
    "사이트맵.",
    "관련 제품",
    "쉬메일",
    "·",
    "전체장편",
    "스카크",
    "스크랩",
    "아들의 a-bitch",
    "스펀지",
    "t1티",
    "시험대",
    "가슴5",
    "tittiefucker의",
    "tittyfuck의",
    "영국",
    "titwank의",
    "v14그라",
    "v1그라",
    "뱅커",
    "pt",
    "5",
    "arrumos",
    "bunda",
    "filho da puta",
    "julgo",
    "o quê",
    "- o quê",
    "como $",
    "a $s",
    "b00",
    "b1",
    "saco de bola",
    "sacana",
    "bestialidade",
    "amigos",
    "bi-ch",
    "cabrão",
    "cadelas",
    "sangrento",
    "broche",
    "broches",
    "boa sorte",
    "bolo",
    "osso",
    "mamas",
    "peitos",
    "mas..",
    "bundas",
    "mastplug",
    "c0m",
    "não",
    "claire",
    "clérigos",
    "amendoim",
    "caralho",
    "cara de pau",
    "cabeça de pau",
    "galão",
    "carpinteiro",
    "paus",
    "pausucked",
    "pausucking",
    "pausuka",
    "colheitadeira",
    "o que é que se passa",
    "cláudia",
    "porra",
    "de verão",
    "com licença",
    "cúpula",
    "não sei",
    "o que é isso",
    "incômodo",
    "cúmplices",
    "cialis",
    "cibercriminoso",
    "os cibercriminosos",
    "maldição",
    "pauzinho",
    "dirsança",
    "dl",
    "cãozinho",
    "- não",
    "duquesa",
    "ejaculações",
    "ejaculada",
    "ejaculando",
    "ejaculação",
    "ejaculação interna",
    "f4b",
    "fagão",
    "fantoche",
    "gorda",
    "pateta",
    "fodido",
    "filhos da puta",
    "foda-se",
    "fodida",
    "cabrões",
    "caralhos",
    "fodas",
    "cortina",
    "eu sei",
    "jogos de vestir",
    "gay",
    "cabras",
    "raios",
    "excitado",
    "sexo quente",
    "tudo bem",
    "jismo",
    "júnior",
    "botão",
    "cabeça de cabeça",
    "- sim",
    "i3i+ch",
    "i3",
    "laboratório",
    "brilho",
    "lustrando",
    "o que fazer",
    "mestre-bate",
    "masterbação",
    "masturbar-se",
    "o que se passa",
    "que se lixe",
    "fodendo",
    "merdas",
    "filho da mãe",
    "muthafecer",
    "fode-se",
    "o que foi",
    "os pretos",
    "o que é",
    "preto",
    "pretos",
    "no",
    "boa noite",
    "nozes",
    "pão",
    "pênis",
    "pênisfucker",
    "telefonesex",
    "a tremer",
    "phuras",
    "pimpos",
    "miúda",
    "miúdo",
    "pias",
    "imposição",
    "mijando",
    "cocó",
    "pornô",
    "por favor",
    "pornografia",
    "pimba",
    "cricks",
    "bar",
    "puxa",
    "puxas",
    "cona",
    "conas",
    "retirada",
    "bordas",
    "sádico",
    "parafusos",
    "sémen",
    "mais",
    "shema",
    "brilhante",
    "t1t",
    "t",
    "não te metas",
    "titã",
    "titãs",
    "que merda",
    "turva",
    "v14g",
    "via satélite",
    "vamos",
    "ru",
    "5хит",
    "55",
    "анальный",
    "анус",
    "аррс",
    "задница",
    "задницы",
    "ублюдок",
    "асфукка",
    "придурок",
    "придурки",
    "полный",
    "как $",
    "б/ч",
    "00бс",
    "17ч",
    "мешок с мячом",
    "шары",
    "мешок",
    "звериный",
    "звериность",
    "колокольчик",
    "скотство",
    "би+ч",
    "двустворчатый",
    "сука",
    "сукин сын",
    "шлюха",
    "шлюхи",
    "стервы",
    "стерва",
    "кровавый",
    "минет",
    "буйвол",
    "боллок",
    "буллок",
    "костлявый",
    "сиська",
    "сиськи",
    "болваны",
    "грудь",
    "буцета",
    "говнюк",
    "дерьмо",
    "бродяга",
    "болван",
    "затвор",
    "вес",
    "мудак",
    "топор",
    "ерунда",
    "шипа",
    "клит",
    "клитор",
    "клиты",
    "кнут",
    "член",
    "петух",
    "лицо члена",
    "членоголовый",
    "членосос",
    "петухи",
    "хулиган",
    "сосать член",
    "членсука",
    "кокс",
    "кумунчер",
    "кексука",
    "кун",
    "кум",
    "колоть",
    "кумминг",
    "кумс",
    "кумшот",
    "кунилингус",
    "куниллингус",
    "куннилингус",
    "пизда",
    "щекотать",
    "щекотливый",
    "пиздец",
    "циалис",
    "киберфук",
    "кибер-трах",
    "киберпроклятый",
    "киберпреступник",
    "киберпреступники",
    "кибер-ебать",
    "1кк",
    "проклятый",
    "фаллоимитатор",
    "ворчать",
    "помойка",
    "дирша",
    "собачий",
    "собака",
    "оселовоз",
    "душ",
    "герцог",
    "дамба",
    "эякулировать",
    "эякулированный",
    "эякулирует",
    "эякулирующий",
    "эякуляция",
    "4nny",
    "педик",
    "педикюр",
    "педики",
    "фагот",
    "фаготы",
    "фанатичный",
    "фаннифлапс",
    "толстый",
    "фук",
    "засранец",
    "грязь",
    "хуй",
    "сволочь",
    "откидывание",
    "сорняк",
    "фелляция",
    "сраный пальцем",
    "ублюдки",
    "гребаный палец",
    "пальчики",
    "сраный",
    "долбаный",
    "фланцеобразный",
    "обман",
    "фукер",
    "ебать",
    "трахаться",
    "ебаный",
    "гребаный",
    "чертов ублюдок",
    "блядь",
    "фуккин",
    "фуквист",
    "приправа",
    "бандаж",
    "бандитизм",
    "бандиты",
    "гей-лорд",
    "гейсекс",
    "козел",
    "черт возьми",
    "хардкорекс",
    "голова",
    "хриплый",
    "кабак",
    "горшок",
    "мотыга",
    "гомо",
    "обнимать",
    "самый роговой",
    "роговой",
    "секс",
    "отсрочка",
    "рывок",
    "яблочный",
    "джизм",
    "джиза",
    "бегство",
    "шипение",
    "лаять",
    "бездельник",
    "ручка",
    "тупица",
    "неряшливый",
    "кнопка",
    "стучать",
    "кондум",
    "кондумы",
    "куммер",
    "3ч",
    "лабиринт",
    "похоть",
    "m45terterate",
    "ма5тербат",
    "мазохист",
    "мастер-бит",
    "мастер8",
    "мастербат",
    "мастерить",
    "мастербирование",
    "мастербации",
    "мастурбировать",
    "мофо",
    "мафия",
    "фото",
    "молоток",
    "мотафук",
    "мотафак",
    "мотылек",
    "усатый",
    "мотафакер",
    "мотафакеры",
    "мотафакин",
    "молохвост",
    "кекс",
    "мутхафекер",
    "нацистский",
    "нигга",
    "ниггер",
    "ниггеры",
    "ниггаз",
    "негр",
    "ноб",
    "нобджоки",
    "бежокей",
    "обезболивающие",
    "гайка",
    "оргазм",
    "рог",
    "пешка",
    "пенис",
    "пенисовец",
    "телефоны",
    "фак",
    "обожженный",
    "пыхтение",
    "пьяный",
    "пьянство",
    "паук",
    "сутенер",
    "моча",
    "разозленный",
    "порох",
    "поршни",
    "сосульки",
    "пессина",
    "отстой",
    "какашка",
    "порно",
    "порнография",
    "уколы",
    "наклон",
    "лоб",
    "гной",
    "пусси",
    "киска",
    "прямая кишка",
    "отсталый",
    "римжа",
    "обрамление",
    "с.о.б.",
    "садист",
    "шлонг",
    "облажаться",
    "горло",
    "писать",
    "мошонка",
    "сперма",
    "ше! +",
    "блин",
    "шт",
    "дрожать",
    "шаггин",
    "женщина",
    "ши+",
    "дерьмовый",
    "говнюки",
    "смегма",
    "смута",
    "похищать",
    "пак",
    "отрыжка",
    "т1тис",
    "трость",
    "тез",
    "тестовый",
    "яичко",
    "сиськи5",
    "чокнутый",
    "титванк",
    "тоссер",
    "v14гра",
    "v1гра",
    "влагалище",
    "виагра",
    "вульва",
    "00се",
    "ван",
    "дрочить",
    "вялый",
    "вор",
    "мухи",
    "волей",
    "zh",
    "4r5e (4r5e) (韩语)",
    "5小时1小时",
    "5发",
    "a55个",
    "肛门",
    "轨道5e",
    "皮肤",
    "屁股",
    "他妈的",
    "驴",
    "阿斯福卡语name",
    "混帐",
    "屁股整齐",
    "(单位:美元)",
    "作为美元",
    "ch",
    "页:1",
    "b17ch (英语)",
    "b1吨级",
    "球囊",
    "球头",
    "鸡巴",
    "杂种",
    "兽形",
    "兽性",
    "铃声",
    "最佳状态",
    "质量",
    "双倍径",
    "双节",
    "贱人",
    "婊子们",
    "骂人",
    "该死的",
    "吹箫",
    "bo",
    "胡说",
    "波罗克",
    "骨头",
    "嘘声",
    "乳头",
    "嘘嘘",
    "布鲁塞塔",
    "可恶",
    "废话",
    "流浪汉",
    "臀部",
    "屁眼",
    "枪托",
    "c0ck (英语)",
    "aw",
    "中国",
    "齐巴",
    "cl1t 键",
    "阴蒂",
    "果实",
    "鸡巴脸",
    "鸡头",
    "鸡尾酒",
    "公鸡",
    "鸡鸡",
    "库克",
    "库克门彻",
    "库克萨",
    "铜",
    "缩写",
    "积分",
    "弯曲",
    "累积射击",
    "阴囊",
    "库尼灵格斯",
    "阴间",
    "贱货",
    "低调",
    "ya",
    "网络福克",
    "网络操",
    "网络他妈的",
    "网络混蛋",
    "d1ck (英语)",
    "蠢货",
    "迪尔多",
    "二极管",
    "叮当",
    "日数a",
    "烂透了",
    "狗娘养的",
    "狗语",
    "养狗",
    "驴肋架",
    "杜许",
    "杜彻",
    "堤坝",
    "射线",
    "射精术",
    "标记",
    "f4ny (英语)",
    "同性恋",
    "发牢骚",
    "粪便",
    "风扇",
    "扇形叶片",
    "你个混蛋",
    "迷恋",
    "肥猪",
    "fcuk (英语)",
    "鸡肉",
    "欢呼",
    "呕吐",
    "堕落",
    "口交时",
    "手指他妈的",
    "指头",
    "拳头操",
    "拳头他妈的",
    "拳头",
    "他妈的拳头",
    "花纹",
    "恶棍",
    "他妈的混蛋",
    "他妈的我",
    "妈的",
    "软糖包装机",
    "乌克",
    "福尔克",
    "乌克金",
    "烟花",
    "乌克维特",
    "阴茎",
    "furx0r (英语)",
    "黑帮",
    "帮派",
    "同性恋者",
    "山羊队",
    "天杀的",
    "硬核性行为",
    "头部",
    "桨",
    "爱",
    "吼声",
    "鹅",
    "高尔",
    "角最强",
    "角质",
    "热性",
    "骗局",
    "贾宝玉",
    "jism 语句",
    "吉兹",
    "坐标",
    "键",
    "针叶",
    "已锁定",
    "旋钮",
    "旋钮头",
    "键盘",
    "鸡",
    "宽度",
    "库姆",
    "ku",
    "单位",
    "库林斯",
    "l3i+ch 键",
    "ưμ㼯a",
    "阴唇",
    "欲望",
    "淫荡",
    "m0f0 时",
    "m0fo 数据",
    "m45 位点",
    "ma5terb8 键",
    "半径",
    "虐恋狂",
    "主减法",
    "主机b8",
    "高级项目*",
    "高级bat3",
    "高级",
    "掌握",
    "手淫",
    "mo",
    "摩尔福",
    "调味料",
    "摩塔他妈的",
    "灭鼠机",
    "马夫",
    "变种人",
    "无",
    "n1gger (英语)",
    "纳粹",
    "零点3r",
    "ni4h",
    "黑鬼",
    "唉哟",
    "黑鬼们",
    "纳吉",
    "黑头",
    "头",
    "无趣",
    "无名",
    "麻核",
    "疯子",
    "质子",
    "矫形",
    "高潮",
    "p0rn 语录",
    "啄木鸟",
    "电话",
    "发球",
    "福尔",
    "划开",
    "摇摆",
    "发声",
    "p",
    "猪头",
    "皮条客",
    "撒尿",
    "愤怒",
    "尿裤子",
    "撒尿器",
    "小便便便便便时",
    "细小的叶片",
    "神经病",
    "便便",
    "色情电影",
    "色情制品",
    "刺头",
    "专业",
    "普丝",
    "猫咪",
    "娘们",
    "阴道",
    "直肠",
    "迟钝",
    "连环画",
    "旋转",
    "绍乙.",
    "虐待狂",
    "长",
    "划伤",
    "切开",
    "精液",
    "性别",
    "嘘 +",
    "嘘",
    "小时",
    "萨格",
    "抖动",
    "变形",
    "做爱",
    "女同性恋",
    "shi+ 键",
    "拉屎了",
    "屎东西",
    "乱七八糟",
    "大便师",
    "乱七八糟的",
    "荡妇",
    "斯迈格马",
    "闪烁",
    "抢",
    "沉积",
    "t1tt1e5 键",
    "吨数",
    "垫子",
    "泰兹语name",
    "测试",
    "睾丸",
    "奶头",
    "奶头5",
    "奶妈",
    "掷掷器",
    "tw4吨级",
    "wa",
    "wa头",
    "watt",
    "v14gra (英语)",
    "v1 颜色",
    "via草",
    "转数",
    "黄",
    "闲着",
    "虚无",
    "妇人",
    "威尔"
]
