// WARNING: this file contains profanity. The below list of profane words is necessary for this tool to function properly.
// Do not read below this line if you do not wish to be exposed to lots of profane words 

const wordsMap = new Map([
    [
        "english",
        [
            "4r5e",
            "5h1t",
            "5hit",
            "a55",
            "anal",
            "anus",
            "ar5e",
            "arrse",
            "arse",
            "arses",
            "ass",
            "ass-fucker",
            "asses",
            "assfucker",
            "assfukka",
            "asshole",
            "assholes",
            "asswhole",
            "a_s_s",
            "a$$",
            "as$",
            "a$s",
            "b!tch",
            "b00bs",
            "b17ch",
            "b1tch",
            "ballbag",
            "balls",
            "ballsack",
            "bastard",
            "beastial",
            "beastiality",
            "bellend",
            "bestial",
            "bestiality",
            "bi+ch",
            "biatch",
            "bitch",
            "bitchboy",
            "bitcher",
            "bitchers",
            "bitches",
            "bitchin",
            "bitching",
            "bloody",
            "blow job",
            "blowjob",
            "blowjobs",
            "boiolas",
            "bollock",
            "bollok",
            "boner",
            "boob",
            "boobs",
            "booobs",
            "boooobs",
            "booooobs",
            "booooooobs",
            "breasts",
            "buceta",
            "bugger",
            "bullshit",
            "bum",
            "butt",
            "butts",
            "butthole",
            "buttmuch",
            "buttplug",
            "c0ck",
            "c0cksucker",
            "carpet muncher",
            "cawk",
            "chink",
            "cipa",
            "cl1t",
            "clit",
            "clitoris",
            "clits",
            "cnut",
            "cock",
            "cock-sucker",
            "cockface",
            "cockhead",
            "cockmunch",
            "cockmuncher",
            "cocks",
            "cocksuck",
            "cocksucked",
            "cocksucker",
            "cocksucking",
            "cocksucks",
            "cocksuka",
            "cocksukka",
            "cok",
            "cokmuncher",
            "coksucka",
            "coon",
            "cox",
            "crap",
            "cum",
            "cummer",
            "cumming",
            "cums",
            "cumshot",
            "cunilingus",
            "cunillingus",
            "cunnilingus",
            "cunt",
            "cuntlick",
            "cuntlicker",
            "cuntlicking",
            "cunts",
            "cyalis",
            "cyberfuc",
            "cyberfuck",
            "cyberfucked",
            "cyberfucker",
            "cyberfuckers",
            "cyberfucking",
            "d1ck",
            "damn",
            "dick",
            "dickhead",
            "dildo",
            "dildos",
            "dink",
            "dinks",
            "dirsa",
            "dlck",
            "dog-fucker",
            "doggin",
            "dogging",
            "donkeyribber",
            "doosh",
            "duche",
            "dyke",
            "ejaculate",
            "ejaculated",
            "ejaculates",
            "ejaculating",
            "ejaculatings",
            "ejaculation",
            "ejakulate",
            "f u c k",
            "f u c k e r",
            "f4nny",
            "fag",
            "fagging",
            "faggitt",
            "faggot",
            "faggs",
            "fagot",
            "fagots",
            "fags",
            "fanny",
            "fannyflaps",
            "fannyfucker",
            "fanyy",
            "fatass",
            "fcuk",
            "fcuker",
            "fcuking",
            "feck",
            "fecker",
            "felching",
            "fellate",
            "fellatio",
            "fingerfuck",
            "fingerfucked",
            "fingerfucker",
            "fingerfuckers",
            "fingerfucking",
            "fingerfucks",
            "fistfuck",
            "fistfucked",
            "fistfucker",
            "fistfuckers",
            "fistfucking",
            "fistfuckings",
            "fistfucks",
            "flange",
            "fook",
            "fooker",
            "fuck",
            "fucka",
            "fucked",
            "fucker",
            "fuckers",
            "fuckhead",
            "fuckheads",
            "fuckin",
            "fucking",
            "fuckings",
            "fuckingshitmotherfucker",
            "fuckme",
            "fucks",
            "fuckwhit",
            "fuckwit",
            "fudge packer",
            "fudgepacker",
            "fuk",
            "fuker",
            "fukker",
            "fukkin",
            "fuks",
            "fukwhit",
            "fukwit",
            "fux",
            "fux0r",
            "f_u_c_k",
            "gangbang",
            "gangbanged",
            "gangbangs",
            "gaylord",
            "gaysex",
            "goatse",
            "god-dam",
            "god-damned",
            "goddamn",
            "goddamned",
            "hardcoresex",
            "headass",
            "hoar",
            "hoare",
            "hoer",
            "hoes",
            "homo",
            "hore",
            "horniest",
            "horny",
            "hotsex",
            "jack-off",
            "jackoff",
            "jap",
            "jerk-off",
            "jism",
            "jiz",
            "jizm",
            "jizz",
            "kawk",
            "knobead",
            "knobed",
            "knobend",
            "knobhead",
            "knobjocky",
            "knobjokey",
            "kock",
            "kondum",
            "kondums",
            "kum",
            "kummer",
            "kumming",
            "kums",
            "kunilingus",
            "l3i+ch",
            "l3itch",
            "labia",
            "lust",
            "lusting",
            "m0f0",
            "m0fo",
            "m45terbate",
            "ma5terb8",
            "ma5terbate",
            "masochist",
            "master-bate",
            "masterb8",
            "masterbat*",
            "masterbat3",
            "masterbate",
            "masterbation",
            "masterbations",
            "masturbate",
            "mo-fo",
            "mof0",
            "mofo",
            "mothafuck",
            "mothafucka",
            "mothafuckas",
            "mothafuckaz",
            "mothafucked",
            "mothafucker",
            "mothafuckers",
            "mothafuckin",
            "mothafucking",
            "mothafuckings",
            "mothafucks",
            "motherfuck",
            "motherfucked",
            "motherfucker",
            "motherfuckers",
            "motherfuckin",
            "motherfucking",
            "motherfuckings",
            "motherfuckka",
            "motherfucks",
            "muff",
            "muthafecker",
            "muthafuckker",
            "mutherfucker",
            "n1gga",
            "n1gger",
            "nazi",
            "nigg3r",
            "nigg4h",
            "nigga",
            "niggah",
            "niggas",
            "niggaz",
            "nigger",
            "niggers",
            "nob",
            "nob jokey",
            "nobhead",
            "nobjocky",
            "nobjokey",
            "numbnuts",
            "nutsack",
            "orgasim",
            "orgasims",
            "orgasm",
            "orgasms",
            "p0rn",
            "pawn",
            "pecker",
            "penis",
            "penisfucker",
            "phonesex",
            "phuck",
            "phuk",
            "phuked",
            "phuking",
            "phukked",
            "phukking",
            "phuks",
            "phuq",
            "pigfucker",
            "pimpis",
            "piss",
            "pissed",
            "pisser",
            "pissers",
            "pisses",
            "pissflaps",
            "pissin",
            "pissing",
            "pissoff",
            "poop",
            "porn",
            "porno",
            "pornography",
            "pornos",
            "prick",
            "pricks",
            "pron",
            "pube",
            "pusse",
            "pussi",
            "pussies",
            "pussy",
            "pussys",
            "rectum",
            "retard",
            "rimjaw",
            "rimming",
            "s hit",
            "s.o.b.",
            "sadist",
            "schlong",
            "screwing",
            "scroat",
            "scrote",
            "scrotum",
            "semen",
            "sex",
            "sh!+",
            "sh!t",
            "sh1t",
            "shag",
            "shagger",
            "shaggin",
            "shagging",
            "shemale",
            "shi+",
            "shit",
            "shitdick",
            "shite",
            "shited",
            "shitey",
            "shitfuck",
            "shitfull",
            "shithead",
            "shiting",
            "shitings",
            "shits",
            "shitted",
            "shitter",
            "shitters",
            "shitting",
            "shittings",
            "shitty",
            "skank",
            "slut",
            "sluts",
            "smegma",
            "smut",
            "snatch",
            "son-of-a-bitch",
            "spac",
            "spunk",
            "s_h_i_t",
            "t1tt1e5",
            "t1tties",
            "teets",
            "teez",
            "testical",
            "testicle",
            "tit",
            "titfuck",
            "tits",
            "titt",
            "tittie5",
            "tittiefucker",
            "titties",
            "tittyfuck",
            "tittywank",
            "titwank",
            "tosser",
            "turd",
            "tw4t",
            "twat",
            "twathead",
            "twatty",
            "twunt",
            "twunter",
            "v14gra",
            "v1gra",
            "vagina",
            "viagra",
            "vulva",
            "w00se",
            "wang",
            "wank",
            "wanker",
            "wanky",
            "whoar",
            "whore",
            "willies",
            "willy",
            "ahole",
            "ash0le",
            "ash0les",
            "asholes",
            "Ass Monkey",
            "Assface",
            "assh0le",
            "assh0lez",
            "assholz",
            "asswipe",
            "azzhole",
            "bassterds",
            "bastards",
            "bastardz",
            "basterds",
            "basterdz",
            "Biatch",
            "Blow Job",
            "boffing",
            "buttwipe",
            "c0cks",
            "c0k",
            "Carpet Muncher",
            "cawks",
            "Clit",
            "cnts",
            "cntz",
            "cock-head",
            "CockSucker",
            "cuntz",
            "dild0",
            "dild0s",
            "dilld0",
            "dilld0s",
            "dominatricks",
            "dominatrics",
            "dominatrix",
            "enema",
            "fag1t",
            "faget",
            "fagg1t",
            "faggit",
            "fagg0t",
            "fagit",
            "fagz",
            "faig",
            "faigs",
            "fart",
            "flipping the bird",
            "Fudge Packer",
            "Fukah",
            "Fuken",
            "Fukin",
            "Fukk",
            "Fukkah",
            "Fukken",
            "Fukker",
            "Fukkin",
            "g00k",
            "God-damned",
            "h00r",
            "h0ar",
            "h0re",
            "hells",
            "hoor",
            "hoore",
            "japs",
            "jisim",
            "jiss",
            "knob",
            "knobs",
            "knobz",
            "kunt",
            "kunts",
            "kuntz",
            "Lezzian",
            "Lipshits",
            "Lipshitz",
            "masokist",
            "massterbait",
            "masstrbait",
            "masstrbate",
            "masterbaiter",
            "masterbates",
            "Motha Fucker",
            "Motha Fuker",
            "Motha Fukkah",
            "Motha Fukker",
            "Mother Fucker",
            "Mother Fukah",
            "Mother Fuker",
            "Mother Fukkah",
            "Mother Fukker",
            "mother-fucker",
            "Mutha Fucker",
            "Mutha Fukah",
            "Mutha Fuker",
            "Mutha Fukkah",
            "Mutha Fukker",
            "n1gr",
            "nastt",
            "nigger;",
            "nigur;",
            "niiger;",
            "niigr;",
            "orafis",
            "orgasim;",
            "orgasum",
            "oriface",
            "orifice",
            "orifiss",
            "packi",
            "packie",
            "packy",
            "paki",
            "pakie",
            "paky",
            "peeenus",
            "peeenusss",
            "peenus",
            "peinus",
            "pen1s",
            "penas",
            "penis-breath",
            "penus",
            "penuus",
            "Phuc",
            "Phuck",
            "Phuk",
            "Phuker",
            "Phukker",
            "polac",
            "polack",
            "polak",
            "Poonani",
            "pr1c",
            "pr1ck",
            "pr1k",
            "pussee",
            "puuke",
            "puuker",
            "recktum",
            "scank",
            "sexy",
            "Sh!t",
            "sh1ter",
            "sh1ts",
            "sh1tter",
            "sh1tz",
            "Shitty",
            "Shity",
            "shitz",
            "Shyt",
            "Shyte",
            "Shytty",
            "Shyty",
            "skanck",
            "skankee",
            "skankey",
            "skanks",
            "Skanky",
            "slag",
            "Slutty",
            "slutz",
            "va1jina",
            "vag1na",
            "vagiina",
            "vaj1na",
            "vajina",
            "vullva",
            "w0p",
            "wh00r",
            "wh0re",
            "xrated",
            "xxx",
            "b!+ch",
            "arschloch",
            "*damn",
            "*dyke",
            "*fuck*",
            "*shit*",
            "@$$",
            "amcik",
            "andskota",
            "arse*",
            "assrammer",
            "ayir",
            "bi7ch",
            "bitch*",
            "bollock*",
            "butt-pirate",
            "cabron",
            "cazzo",
            "chraa",
            "chuj",
            "Cock*",
            "cunt*",
            "d4mn",
            "daygo",
            "dego",
            "dick*",
            "dike*",
            "dupa",
            "dziwka",
            "ejackulate",
            "Ekrem*",
            "Ekto",
            "enculer",
            "faen",
            "fag*",
            "fanculo",
            "feces",
            "feg",
            "Felcher",
            "ficken",
            "fitt*",
            "Flikker",
            "foreskin",
            "Fotze",
            "Fu(*",
            "fuk*",
            "futkretzn",
            "gook",
            "guiena",
            "h0r",
            "h4x0r",
            "hell",
            "helvete",
            "hoer*",
            "honkey",
            "Huevon",
            "hui",
            "injun",
            "kanker*",
            "kike",
            "klootzak",
            "kraut",
            "knulle",
            "kuk",
            "kuksuger",
            "Kurac",
            "kurwa",
            "kusi*",
            "kyrpa*",
            "lesbo",
            "mamhoon",
            "masturbat*",
            "merd*",
            "mibun",
            "monkleigh",
            "mouliewop",
            "muie",
            "mulkku",
            "muschi",
            "nazis",
            "nepesaurio",
            "nigger*",
            "orospu",
            "paska*",
            "perse",
            "picka",
            "pierdol*",
            "pillu*",
            "pimmel",
            "piss*",
            "pizda",
            "poontsee",
            "pr0n",
            "preteen",
            "pula",
            "pule",
            "puta",
            "puto",
            "qahbeh",
            "queef*",
            "rautenberg",
            "schaffer",
            "scheiss*",
            "schlampe",
            "schmuck",
            "screw",
            "sh!t*",
            "sharmuta",
            "sharmute",
            "shipal",
            "shiz",
            "skribz",
            "skurwysyn",
            "sphencter",
            "spic",
            "spierdalaj",
            "splooge",
            "suka",
            "b00b*",
            "testicle*",
            "titt*",
            "vittu",
            "wank*",
            "wetback*",
            "wichser",
            "wop*",
            "yed",
            "zabourah",
        ],
    ],
    [
        "hindi",
        [
            "aad",
            "aand",
            "bahenchod",
            "behenchod",
            "bhenchod",
            "bhenchodd",
            "b.c.",
            "bc",
            "bakchod",
            "bakchodd",
            "bakchodi",
            "bevda",
            "bewda",
            "bevdey",
            "bewday",
            "bevakoof",
            "bevkoof",
            "bevkuf",
            "bewakoof",
            "bewkoof",
            "bewkuf",
            "bhadua",
            "bhaduaa",
            "bhadva",
            "bhadvaa",
            "bhadwa",
            "bhadwaa",
            "bhosada",
            "bhosda",
            "bhosdaa",
            "bhosdike",
            "bhonsdike",
            "bsdk",
            "b.s.d.k",
            "bhosdiki",
            "bhosdiwala",
            "bhosdiwale",
            "bhosadchodal",
            "bhosadchod",
            "babbe",
            "babbey",
            "bube",
            "bubey",
            "bur",
            "burr",
            "buurr",
            "buur",
            "charsi",
            "chooche",
            "choochi",
            "chuchi",
            "chhod",
            "chod",
            "chodd",
            "chudne",
            "chudney",
            "chudwa",
            "chudwaa",
            "chudwane",
            "chudwaane",
            "choot",
            "chut",
            "chute",
            "chutia",
            "chutiya",
            "chutiye",
            "chuttad",
            "chutad",
            "dalaal",
            "dalal",
            "dalle",
            "dalley",
            "fattu",
            "gadha",
            "gadhe",
            "gadhalund",
            "gaand",
            "gand",
            "gandu",
            "gandfat",
            "gandfut",
            "gandiya",
            "gandiye",
            "gote",
            "gotey",
            "gotte",
            "hag",
            "haggu",
            "hagne",
            "hagney",
            "harami",
            "haramjada",
            "haraamjaada",
            "haramzyada",
            "haraamzyaada",
            "haraamjaade",
            "haraamzaade",
            "haraamkhor",
            "haramkhor",
            "jhat",
            "jhaat",
            "jhaatu",
            "jhatu",
            "kutta",
            "kutte",
            "kuttey",
            "kutia",
            "kutiya",
            "kuttiya",
            "kutti",
            "landi",
            "landy",
            "laude",
            "laudey",
            "laura",
            "lora",
            "lauda",
            "ling",
            "loda",
            "lode",
            "lund",
            "launda",
            "lounde",
            "laundey",
            "laundi",
            "loundi",
            "laundiya",
            "loundiya",
            "lulli",
            "maar",
            "maro",
            "marunga",
            "madarchod",
            "madarchodd",
            "madarchood",
            "madarchoot",
            "madarchut",
            "m.c.",
            "mc",
            "mamme",
            "mammey",
            "moot",
            "mut",
            "mootne",
            "mutne",
            "mooth",
            "muth",
            "nunni",
            "nunnu",
            "paaji",
            "paji",
            "pesaab",
            "pesab",
            "peshaab",
            "peshab",
            "pilla",
            "pillay",
            "pille",
            "pilley",
            "pisaab",
            "pisab",
            "pkmkb",
            "porkistan",
            "raand",
            "rand",
            "randi",
            "randy",
            "suar",
            "tatte",
            "tatti",
            "tatty",
            "ullu",
            "आंड़",
            "आंड",
            "आँड",
            "बहनचोद",
            "बेहेनचोद",
            "भेनचोद",
            "बकचोद",
            "बकचोदी",
            "बेवड़ा",
            "बेवड़े",
            "बेवकूफ",
            "भड़ुआ",
            "भड़वा",
            "भोसड़ा",
            "भोसड़ीके",
            "भोसड़ीकी",
            "भोसड़ीवाला",
            "भोसड़ीवाले",
            "भोसरचोदल",
            "भोसदचोद",
            "भोसड़ाचोदल",
            "भोसड़ाचोद",
            "बब्बे",
            "बूबे",
            "बुर",
            "चरसी",
            "चूचे",
            "चूची",
            "चुची",
            "चोद",
            "चुदने",
            "चुदवा",
            "चुदवाने",
            "चूत",
            "चूतिया",
            "चुटिया",
            "चूतिये",
            "चुत्तड़",
            "चूत्तड़",
            "दलाल",
            "दलले",
            "फट्टू",
            "गधा",
            "गधे",
            "गधालंड",
            "गांड",
            "गांडू",
            "गंडफट",
            "गंडिया",
            "गंडिये",
            "गू",
            "गोटे",
            "हग",
            "हग्गू",
            "हगने",
            "हरामी",
            "हरामजादा",
            "हरामज़ादा",
            "हरामजादे",
            "हरामज़ादे",
            "हरामखोर",
            "झाट",
            "झाटू",
            "कुत्ता",
            "कुत्ते",
            "कुतिया",
            "कुत्ती",
            "लेंडी",
            "लोड़े",
            "लौड़े",
            "लौड़ा",
            "लोड़ा",
            "लौडा",
            "लिंग",
            "लोडा",
            "लोडे",
            "लंड",
            "लौंडा",
            "लौंडे",
            "लौंडी",
            "लौंडिया",
            "लुल्ली",
            "मार",
            "मारो",
            "मारूंगा",
            "मादरचोद",
            "मादरचूत",
            "मादरचुत",
            "मम्मे",
            "मूत",
            "मुत",
            "मूतने",
            "मुतने",
            "मूठ",
            "मुठ",
            "नुननी",
            "नुननु",
            "पाजी",
            "पेसाब",
            "पेशाब",
            "पिल्ला",
            "पिल्ले",
            "पिसाब",
            "पोरकिस्तान",
            "रांड",
            "रंडी",
            "सुअर",
            "सूअर",
            "टट्टे",
            "टट्टी",
            "उल्लू",
            "4r5e",
            "5h1t",
            "5hit",
            "a55",
            "गुदामैथुन",
            "एनस",
            "ar5e",
            "arrse",
            "आर्सेना",
            "शस्त्र",
            "ass",
            "ass-fucker",
            "assfucker",
            "assfukka",
            "asshole",
            "assholes",
            "asswhole",
            "$$",
            "$",
            "b",
            "b00b",
            "b17ch",
            "b1tch",
            "बॉलबैग",
            "गेंद",
            "गेंदों",
            "बस्टर्ड",
            "जानवर",
            "समानता",
            "घंटी",
            "श्रेष्ठ",
            "श्रेष्ठता",
            "bi+ch",
            "बिच",
            "बिटच",
            "चूंचियां",
            "बिटचर",
            "बिट्च",
            "बिटचिन",
            "बिटिंग",
            "खूनी",
            "blow job",
            "blowjob",
            "बियोला",
            "बोल्क",
            "बोललोक",
            "हड्डी",
            "शराब",
            "स्तन",
            "booooobs",
            "buceta",
            "बगीचा",
            "हिन्दी",
            "bum",
            "बट",
            "बटहोल",
            "बटमच",
            "buttplug",
            "c0ck",
            "c0cksucker",
            "carpet muncher",
            "चिंक",
            "cipa",
            "cl1t",
            "क्लिट",
            "क्लिटोरिस",
            "अखरोट",
            "मुर्गा",
            "मुर्गा चूसने वाला",
            "कॉकफेस",
            "कॉक",
            "मुर्गा चूसने",
            "कोक",
            "cokmuncher",
            "coksucka",
            "कोन",
            "केकड़ा",
            "सह",
            "cummer",
            "cumming",
            "कमशॉट",
            "गुलगुला",
            "cunillingus",
            "हिंदी",
            "चाचा",
            "cuntlick",
            "cuntlicker",
            "cuntlicking",
            "cunts",
            "cyalis",
            "साइबरफ़ुक",
            "साइबर बकवास",
            "d1ck",
            "damn",
            "डिक",
            "dickhead",
            "डिल्डो",
            "dildos",
            "गुत्थी",
            "डंक",
            "कुत्ते-fucker",
            "dogging",
            "डोष",
            "डच",
            "डाइक",
            "ejaculate",
            "ejaculated",
            "ejaculation",
            "ejaculations",
            "ejakulate",
            "f u c k",
            "f u c k e r",
            "f4nny",
            "फ़ैग",
            "छूत",
            "चुभोना",
            "fagot",
            "फैनी",
            "फैनीफ्लैप",
            "कट्टर",
            "वसा",
            "fcuk",
            "fcuker",
            "fcuking",
            "fecker",
            "गिरना",
            "गिरती",
            "उंगली करना",
            "fingerfucked",
            "उंगलियों",
            "मुट्ठीकरना",
            "fistfucked",
            "fistfucker",
            "fistfuckers",
            "fistfucking",
            "fistfuck",
            "फुहार",
            "चॉकर",
            "भाड़ में जाओ",
            "बकवास",
            "गड़बड़",
            "मुख-मैथुन",
            "fuckheads",
            "कमबख्त",
            "fuckingshitmotherfucker",
            "fudge packer",
            "fudgepacker",
            "fuk",
            "fucker",
            "fukkin",
            "फक",
            "फूहड़",
            "fux0r",
            "गिरोह बैंग",
            "gangbanged",
            "समलैंगिक",
            "बकरी",
            "देवता",
            "देवी",
            "कट्टरसेक्स",
            "सिर",
            "होर",
            "हो",
            "होम",
            "सींग का",
            "सेक्सी",
            "जैक ऑफ",
            "जैकपॉट",
            "जैप",
            "मरोड़ते",
            "jism",
            "जिज़",
            "जिज़्म",
            "कावा",
            "घुंडी",
            "knobjocky",
            "kock",
            "कोंडोम",
            "कोन्डम",
            "कुम्भ",
            "kumming",
            "गुनगुना",
            "l3i+ch",
            "l3itch",
            "लैबिया",
            "चमकना",
            "m0f0",
            "m0fo",
            "m45terbate",
            "ma5terb8",
            "ma5terbate",
            "मैसोचिस्ट",
            "मास्टर-बेट",
            "मास्टरब8",
            "मास्टरबैट*",
            "मास्टरबैट3",
            "मास्टरबेट",
            "masterbation",
            "हस्तमैथुन",
            "mo-fo",
            "mof0",
            "साइटमैप",
            "mothafucka",
            "mothafuckaz",
            "mothafucked",
            "mothafucker",
            "mothafuckin",
            "mothafucking",
            "माँ",
            "motherfucked",
            "motherfucker",
            "motherfuckers",
            "motherfuckin",
            "motherfucking",
            "motherfuckka",
            "माताओं",
            "माफ",
            "muthafecker",
            "muthafuckker",
            "mutherfucker",
            "n1gga",
            "n1gger",
            "नाज़ी",
            "nigg3r",
            "nigg4h",
            "निगा",
            "निगाह",
            "नागा",
            "nigger",
            "niggers",
            "नोब",
            "nob jokey",
            "नोबहेड",
            "nobjocky",
            "nobjokey",
            "नट्सैक",
            "orgasim",
            "संभोग सुख",
            "p0",
            "मोहन",
            "पेकर",
            "पेनिस",
            "penisfucker",
            "फोनसेक्स",
            "चक",
            "फुक",
            "फुकेत",
            "phuq",
            "pigfucker",
            "पिम्पिस",
            "pissed",
            "pissing",
            "पेशाब करना",
            "पोप",
            "अश्लील",
            "पोर्नोग्राफी",
            "ट्रिक",
            "pricks",
            "प्रोन",
            "पुसी",
            "बिल्ली",
            "राशि",
            "मंदिर",
            "रिमजॉ",
            "rimming",
            "s hit",
            "s.o.b.",
            "sadist",
            "schlong",
            "पेंच",
            "झरना",
            "घूंघट",
            "अंडकोष",
            "वीर्य",
            "सेक्स",
            "sh!+",
            "sh!t",
            "sh1t",
            "shag",
            "shagger",
            "shaggin",
            "shagging",
            "shemale",
            "शि +",
            "shitfuck",
            "shitful",
            "शिटिंग",
            "पतला",
            "शिथिल",
            "शिटर",
            "शिट्टी",
            "skank",
            "गुदगुदी",
            "smegma",
            "smut",
            "छीनना",
            "बेटा",
            "स्पेक",
            "टट्टू",
            "t1t1e5",
            "टी1टी",
            "टी",
            "टीज़",
            "वृषण",
            "तैसा",
            "टिट्स",
            "टिट",
            "tittie5",
            "tittiefucker",
            "titties",
            "tittyfuck",
            "tittywank",
            "titwank",
            "toser",
            "turd",
            "tw4t",
            "twat",
            "twathead",
            "twatty",
            "ट्वंट",
            "ट्वंटर",
            "v14gra",
            "v1gra",
            "योनि",
            "वियाग्रा",
            "vulva",
            "w00se",
            "वांग",
            "wank",
            "wanker",
            "wanky",
            "whoar",
            "whore",
            "इच्छा",
            "Badir",
            "Badirchand",
            "Bakland",
            "Bhandava",
            "Chinaal",
            "Bhoot-nee ka",
            "Chutia",
            "Chutiya",
            "choo-tia",
            "Chutan",
            "Ghasti",
            "gashti",
            "gasti",
            "ghassad",
            "Haraami",
            "Haraam Zaada",
            "Hijda",
            "Hijra",
            "Jaan var",
            "Kutta",
            "Kuttiya",
            "Khota",
            "Khotey ki aulad",
            "Kutte ki jat",
            "Najayaz",
            "Najayaz paidaish",
            "Saala kutta",
            "Saali kutti",
            "Soover",
            "Tatti",
            "Bahenchod",
            "Bahen_Chod",
            "Bahen-Chod",
            "Bahen Chod",
            "Bahen ke laude",
            "Bahen ke takke",
            "Beti Chod",
            "Bhains ki aulad",
            "Jhalla",
            "Faggot",
            "Jhant ke baal",
            "Jhaant ke pissu",
            "Kutte ka aulad",
            "Kutte ke tatte",
            "Maadher chod",
            "Padma",
            "Randhwa",
            "Raand ka jamai",
            "randwa",
            "Rundi",
            "Rundi ka bacha",
            "Rundi Ki bachi",
            "Soower ke bachche",
            "Ullu ke pathe",
            "Bandaa",
            "Booblay",
            "Carrom board",
            "BhonsRi-Waalaa",
            "Chhed",
            "Chut",
            "Chut marike",
            "Chodu",
            "Chodra",
            "Choochii",
            "Gaandu",
            "Gaand",
            "LavDa",
            "Lavde",
            "Lund�",
            "Lavde ke bal",
            "Lavander",
            "Mangachinamun",
            "Muth mar",
            "Bhosad Chod",
            "Bumchod",
            "Cuntmama",
            "Chodela",
            "Gaandfat",
            "Gaandmasti",
            "Ghondoo",
            "Lundoos",
            "Parichod",
            "Pucchi",
        ],
    ],
    [
        "bengali",
        [
            "behaya",
            "betachele",
            "birjo",
            "bokachoda",
            "bounsi",
            "chipa",
            "chiruni",
            "choda",
            "chodachudi",
            "chodai",
            "chodas",
            "chodon",
            "chodonkhor",
            "chud",
            "chuda",
            "chude",
            "chudchis",
            "chudi",
            "chutmarani",
            "condom",
            "dhon",
            "dudh",
            "gadachoda",
            "gali",
            "gorbopat",
            "gud",
            "gud mara",
            "halarput",
            "harami",
            "haramjada",
            "khanki",
            "kuttarbaccha",
            "lawra",
            "lawaura",
            "lêngta",
            "maal",
            "magi",
            "madarchod",
            "nosta",
            "pacha",
            "paknami",
            "poj",
            "rendi",
            "chudon",
            "chut",
            "gaandu",
            "lavra",
            "laura",
            "laoda",
            "laowda",
            "lawda",
            "lawdaaaaa",
            "choddar",
            "magirbaccha",
            "khankirchele",
            "randibaji",
            "fuckni",
            "banchod",
            "banchoo",
            "bosdike",
            "bc",
            "mc",
            "durr",
            "randiwala",
            "chutia",
            "chutiaa",
            "gandmara",
            "chutmara",
            "magipana",
            "chodapona",
            "chodamu",
            "podmara",
            "randikhana",
            "randimarani",
            "dudhmarani",
            "lavda",
            "chutcho",
            "chutiyapa",
            "chutyapa",
            "fuckboy",
            "fuckgirl",
            "চিপা",
            "চিরুনী",
            "চুদ",
            "চুদাই",
            "চুদছিস",
            "চুদা",
            "চুদে",
            "চুদি",
            "চুদনী",
            "চোদা",
            "চোদন",
            "চোদনখোর",
            "চোদস",
            "চোদাচুদি",
            "চুতমারানি",
            "গাধাচোদা",
            "গর্ভপাত",
            "গালি",
            "গুদ",
            "গুদ মারা",
            "খাঙ্কি",
            "খানকি",
            "কন্ডোম",
            "কুত্তারবাচ্চা",
            "ধোন",
            "ধন",
            "নষ্টা",
            "পজ",
            "পাছা",
            "পাকনামি",
            "বেটাছেল",
            "বোকাচোদা",
            "বীর্য",
            "বেহায়া",
            "বাঊন্সি",
            "মাদারচোদ",
            "মাগি",
            "মাল",
            "লাওড়া",
            "ল্যাওড়া",
            "ল্যাংটা",
            "রেন্ডি",
            "হারামজাদা",
            "হারামি",
            "হালারপুত",
            "ভোঁদা",
            "চুদন",
            "বস্তি",
            "লুচ্চা",
            "বজ্জাত",
            "কুত্তি",
            "মাগী",
            "চোদক",
            "চুদাক",
            "গুদফাট",
            "চোদাও",
            "দুধঝরা",
            "পাছামার",
            "হিজড়া",
            "গর্দভ",
            "শুয়োর",
            "গাঁজাখোর",
            "নেশাখোর",
            "উরুমার",
            "বাপচোদ",
            "মা-চোদ",
            "রেন্ডিখানা",
            "ছিঁচকে",
            "পাছাভরা",
        ],
    ],
    [
        "bhojpuri",
        [
            "bhosdi",
            "bhosdike",
            "madarchod",
            "behanchod",
            "chutiya",
            "chutia",
            "lavda",
            "lauda",
            "gand",
            "gandmara",
            "chudai",
            "chuda",
            "chodu",
            "maa ke laude",
            "behan ke lund",
            "randi",
            "randibaaz",
            "chinal",
            "harami",
            "haramzada",
            "rakhail",
            "jhaatu",
            "bhadwa",
            "bhadwe",
            "bhadvi",
            "chut",
            "chutmarani",
            "chutiyapa",
            "gandu",
            "bosdika",
            "kutte",
            "suar",
            "bhenchod",
            "bhonsdiwale",
            "madar",
            "gandfat",
            "jhaant",
            "chuchu",
            "doodh",
            "gaandfat",
            "tel lagwa",
            "randi khaana",
            "भोसड़ी",
            "भोसड़ीके",
            "मादरचोद",
            "बहनचोद",
            "चुतिया",
            "चूतिया",
            "लौड़ा",
            "गांड",
            "गांड मारा",
            "चुदाई",
            "चूदा",
            "चोदू",
            "माँ के लौड़े",
            "बहन के लौड़े",
            "रंडी",
            "रंडीबाज़",
            "चिनाल",
            "हरामी",
            "हरामजादा",
            "रखैल",
            "झाटू",
            "भड़वा",
            "भड़वे",
            "भड़वी",
            "चूत",
            "चूतमारानी",
            "चुतियापा",
            "गांडू",
            "बोसड़ीका",
            "कुत्ते",
            "सूअर",
            "भेंचोद",
            "भोंसड़ीवाले",
            "मादर",
            "गांडफट",
            "झाँट",
            "चूचू",
            "दूध",
            "तेल लगवा",
            "रंडी खाना",
        ],
    ],
    [
        "marathi",
        [
            "chyalya",
            "jhat",
            "jhatu",
            "jhav",
            "jhavla",
            "jhavto",
            "chod",
            "chodla",
            "madarchod",
            "behanchod",
            "gaand",
            "gaandu",
            "gaandphatli",
            "land",
            "lavda",
            "saali",
            "randi",
            "rand",
            "harami",
            "haramkhor",
            "bhosdi",
            "bhosdichi",
            "bhadwa",
            "chut",
            "chutmaar",
            "jhavjhav",
            "jhavne",
            "jhavayla",
            "lavdya",
            "gaandugiri",
            "nalayak",
            "phatki",
            "jhavayla de",
            "bhendi",
            "jhavtoy",
            "jhavayla pahije",
            "veshya",
            "veshyalay",
            "chaddi",
            "lavdat",
            "च्यायला",
            "झाट",
            "झाटू",
            "झव",
            "झवला",
            "झवतो",
            "चोद",
            "चोदला",
            "मादरचोद",
            "बहनचोद",
            "गांड",
            "गांडू",
            "गांडफाटली",
            "लंड",
            "लवडा",
            "साली",
            "रंडी",
            "रांड",
            "हरामी",
            "हरामखोर",
            "भोसडी",
            "भोसडीची",
            "भडवा",
            "चुत",
            "चुतमार",
            "झवझव",
            "झवणे",
            "झवायला",
            "लवड्या",
            "गांडूगिरी",
            "नालायक",
            "फाटकी",
            "झवायला दे",
            "भेंडी",
            "झवतोय",
            "झवायला पाहिजे",
            "वेश्या",
            "वेश्यालय",
            "चड्डी",
            "लवडत",
        ],
    ],
    [
        "assamese",
        [
            "chuda",
            "magi",
            "khonki",
            "madarchod",
            "bhaga",
            "dhon",
            "halarput",
            "gadha",
            "kukurar putek",
            "rendi",
            "bharik",
            "chudoni",
            "pacholor",
            "gali",
            "phuti jaok",
            "chipa",
            "maakchuda",
            "bhoda",
            "jaroj",
            "pach",
            "gorbhopaat",
            "gud",
            "dudh",
            "hagi dim",
            "lawra",
            "khanki",
            "nosta",
            "চুদা",
            "মাগী",
            "খংকি",
            "মাদাৰচোদ",
            "ভগা",
            "ধোন",
            "হালাৰপুত",
            "গধা",
            "কুকুৰৰ পুতেক",
            "ৰেণ্ডি",
            "ভৰিক",
            "চুদনী",
            "পাছলৰ",
            "গালি",
            "ফুটি যাওঁক",
            "চিপা",
            "মাকচুদা",
            "ভোঁদা",
            "জাৰজ",
            "পাছ",
            "গৰ্ভপাত",
            "গুদ",
            "দুধ",
            "লাওড়া",
            "খনকি",
            "নষ্টা",
        ],
    ],
    [
        "chhattisgarhi",
        [
            "chut",
            "chutiyapa",
            "chutiyapanti",
            "chutiyapan",
            "chod",
            "chodai",
            "chodna",
            "chodne",
            "chodne wala",
            "chodne wali",
            "madarchod",
            "madarchodi",
            "madarchodiyan",
            "madarchodiyon",
            "bhosdiwala",
            "bhosdiwali",
            "bhosdiwale",
            "bhosdike",
            "bhosdikiya",
            "bhosdiyon",
            "gaanduu",
            "bhosdi",
            "chudwa",
            "behanchod",
            "land",
            "lavda",
            "napunsak",
            "harami",
            "haramkhor",
            "randi",
            "rand",
            "chutiya",
            "jhaant",
            "gaand",
            "gaandphat",
            "jhavwa",
            "jhaveli",
            "maa ke chod",
            "bahin ke chod",
            "khanjar",
            "jhabra",
            "bhadwa",
            "chutmaar",
            "tatti",
            "phattu",
            "gadhe",
            "kutta",
            "bakrichod",
            "gadhachod",
            "गांडू",
            "भोसड़ी",
            "चुदवा",
            "चुत",
            "भोसड़ीके",
            "मादरचोद",
            "बहनचोद",
            "लंड",
            "लवड़ा",
            "नपुंसक",
            "हरामी",
            "हरामखोर",
            "रंडी",
            "रांड",
            "चुटिया",
            "झांट",
            "गांड",
            "गांडफाट",
            "झववा",
            "झवेली",
            "माई के चोद",
            "बहिनी के चोद",
            "खंजर",
            "झबरा",
            "भड़वा",
            "चूतमार",
            "टट्टी",
            "फट्टू",
            "गधे",
            "कुत्ता",
            "बकरीचोद",
            "गधाचोद",
        ],
    ],
    [
        "gujarati",
        [
            "chut",
            "chutiyapa",
            "chutiyapanti",
            "chutiyapan",
            "chod",
            "chodai",
            "chodna",
            "chodne",
            "chodne wala",
            "chodne wali",
            "madarchod",
            "madarchodi",
            "madarchodiyan",
            "madarchodiyon",
            "bhosdiwala",
            "bhosdiwali",
            "bhosdiwale",
            "bhosdike",
            "bhosdikiya",
            "bhosdiyon",
            "gaanduu",
            "bhosdi",
            "chudwa",
            "behanchod",
            "land",
            "lavda",
            "napunsak",
            "harami",
            "haramkhor",
            "randi",
            "rand",
            "chutiya",
            "jhaant",
            "gaand",
            "gaandphat",
            "chodvama",
            "chudai",
            "lavdo",
            "bhosdichi",
            "bhadvo",
            "bhadvi",
            "bhenschod",
            "gaando",
            "galfado",
            "ghetachod",
            "veshya",
            "nalayak",
            "fatakdi",
            "bhenchod",
            "ચોદ",
            "ચોદવામાં",
            "ચુદાઈ",
            "લંડ",
            "લવડો",
            "ભોસડી",
            "ભોસડીચી",
            "ભડવો",
            "ભડવી",
            "ભેંસચોદ",
            "રંડી",
            "રાંડ",
            "ચુત",
            "ચુતિયો",
            "ચુતિયાપા",
            "ગાંડ",
            "ગાંડફાટ",
            "ગાંડો",
            "હરામી",
            "હરામખોર",
            "ગલફડો",
            "ઘેટાચોદ",
            "વેશ્યા",
            "નાલાયક",
            "ફટાકડી",
            "ભેનચોદ",
            "માદરચોદ",
        ],
    ],
    [
        "kannada",
        [
            "chuchi",
            "chudi",
            "load",
            "londa",
            "maga",
            "chudodru",
            "gaandi",
            "gaand",
            "husharilla",
            "naayi nanda",
            "naayi maga",
            "bus maga",
            "jaari",
            "chuchukattu",
            "ganduhuttu",
            "raandi",
            "dadda",
            "hudugi naayi",
            "lochan",
            "madarchod",
            "behanchod",
            "chootan",
            "hudugana haang",
            "gandukilla",
            "ಚುಚಿ",
            "ಚೂದಿ",
            "ಲೋಡ್",
            "ಲೋಂಡಾ",
            "ಮಾಗ",
            "ಚೂದೋದ್ರು",
            "ಗಾಂಡಿ",
            "ಗಾಂಡ",
            "ಹುಷಾರಿಲ್ಲ",
            "ನಾಯಿ ನಂದಾ",
            "ನಾಯಿ ಮಗ",
            "ಬಸ್ ಮಗ",
            "ಜಾರಿ",
            "ಚುಚುಕಟ್ಟು",
            "ಗಂಡುಹುಟ್ಟು",
            "ರಾಂಡಿ",
            "ದಡ್ಡ",
            "ಹುಡುಗಿ ನಾಯಿ",
            "ಲೋಚನ್",
            "ಮದರ್ಚೋದ್",
            "ಬೆಹನ್ಚೋದ್",
            "ಚೂತನ",
            "ಹುಡುಗನ ಹಾಂಗ್",
            "ಗಂಡುಕಿಲ್ಲ",
        ],
    ],
    [
        "kashmiri",
        [
            "gasti",
            "gadh",
            "bhosdike",
            "lavde",
            "chuda",
            "chus",
            "gand",
            "haramzada",
            "madarchod",
            "behanchod",
            "choor",
            "chu",
            "haraam",
            "gaandu",
            "bhand",
            "gadha",
            "rand",
            "randi",
            "chot",
            "lanjat",
            "kafir",
            "chooti",
            "lawde",
            "saale",
            "yemberzal",
            "yemberzal chu",
            "chus chu",
            "kanjri",
            "randikhor",
            "گسٹی",
            "گدھ",
            "بھوسڈیکے",
            "لانڈے",
            "چود",
            "چوس",
            "گاند",
            "حرامزاده",
            "مدرچود",
            "بہنچود",
            "چور",
            "چو",
            "حرام",
            "گانڈو",
            "بھند",
            "گدھا",
            "رنڈ",
            "رنڈی",
            "چوٹ",
            "لنجت",
            "کافر",
            "چوٹی",
            "لاوڈے",
            "سالے",
            "یمبرزال",
            "یمبرزال چو",
            "چس چو",
            "کنجری",
            "رنڈیکور",
        ],
    ],
    [
        "konkani",
        [
            "madarchod",
            "behanchod",
            "chutiyapa",
            "chutiyapan",
            "chod",
            "chodai",
            "chodne",
            "madarchodi",
            "bhosdiwala",
            "bhosdike",
            "gaanduu",
            "bhosdi",
            "chudwa",
            "chut",
            "land",
            "lavda",
            "napunsak",
            "harami",
            "haramkhor",
            "randi",
            "rand",
            "chutiya",
            "jhaant",
            "gaandphatli",
            "chodu",
            "lavdek",
            "gand",
            "gaandu",
            "kutryacho pisko",
            "fucker",
            "chutmaro",
            "chutya",
            "chutyagiri",
            "baile",
            "dongrapuricho",
            "randicho polo",
            "dhakkya",
            "murdya",
            "bhendicho",
            "चोद",
            "चोडू",
            "लवडा",
            "गांड",
            "गांडू",
            "भोसडी",
            "भोसडीके",
            "मादरचोद",
            "बहनचोद",
            "कुतर्याचो पिस्को",
            "रंडी",
            "चूत",
            "चुतमारो",
            "चुत्या",
            "हरामी",
            "हरामखोर",
            "बाईले",
            "ढक्क्या",
            "मुर्द्या",
        ],
    ],
    [
        "ladakhi",
        [
            "khu",
            "khupa",
            "chingpo",
            "chokpa",
            "nyampa",
            "chipa",
            "tseri",
            "phokpa",
            "shoza",
            "phokchu",
            "chomo",
            "lapchu",
            "fuckpa",
            "chingchok",
            "shingmo",
            "khacha",
            "tchot",
            "laptsa",
            "khatok",
            "shokmo",
            "chozay",
            "ཁུ",
            "ཁུ་པ",
            "ཅིང་པོ",
            "ཅོག་པ",
            "ཉམ་པ",
            "ཅི་པ",
            "ཚེ་རི",
            "ཕོག་པ",
            "ཤོ་ཟ",
            "ཕོག་ཆུ",
            "ཆོ་མོ",
            "ལབ་ཆུ",
            "ཕག་པ",
            "ཅིང་ཅོག",
            "ཤིང་མོ",
            "ཁ་ཆ",
            "ཚོད",
            "ལབ་ཙ",
            "ཁ་ཐོག",
            "ཤོག་མོ",
            "ཆོ་ཟེ",
        ],
    ],
    [
        "malayalam",
        [
            "podi",
            "poda",
            "po ra",
            "patti",
            "patti mon",
            "patti pille",
            "thendi",
            "thendi patti",
            "thendi mon",
            "thendi pille",
            "thekkan",
            "kundi",
            "kundi kuthu",
            "pundiyude",
            "pundiketta",
            "pundiyude makan",
            "pundiyude pille",
            "muthe",
            "muthe mon",
            "muthe pille",
            "tho",
            "thallipoli",
            "behenchod",
            "madarchod",
            "kallanmar",
            "vedi",
            "thallippoli",
            "theval",
            "theveli",
            "chodiyan",
            "thallan",
            "vaangikonda",
            "nayinte makan",
            "nayinte pille",
            "kallan",
            "thendi theval",
            "thendi vedi",
            "thendi thallippoli",
            "thendi thallipoli mon",
            "പൊടി",
            "പൊടാ",
            "പോ റാ",
            "പട്ടി",
            "പട്ടിമോൻ",
            "പട്ടിപിള്ളേ",
            "തെണ്ടി",
            "തെണ്ടി പട്ടി",
            "തെണ്ടിമോൻ",
            "തെണ്ടിപിള്ളേ",
            "തെക്കൻ",
            "കുണ്ടി",
            "കുണ്ടി കുത്ത്",
            "പുണ്ണിയുടെ",
            "പുണ്ടികെട്ട",
            "പുണ്ണിയുടെ മകൻ",
            "പുണ്ണിയുടെ പിള്ളേ",
            "മുതേ",
            "മുതേ മോൻ",
            "മുതേ പിള്ളേ",
            "തോ",
            "തള്ളിപ്പൊളി",
            "ബഹൻചോദ്",
            "മാദർചോദ്",
            "കള്ളന്മാർ",
            "വെടി",
            "തെവൽ",
            "തെവേലി",
            "ചോദിയൻ",
            "തള്ളൻ",
            "വാങ്ങികൊണ്ട",
            "നായിന്റെ മകൻ",
            "നായിന്റെ പിള്ളേ",
            "കള്ളൻ",
            "തെണ്ടി തെവൽ",
            "തെണ്ടി വെടി",
        ],
    ],
    [
        "manipuri",
        [
            "heibak",
            "nangna pukningba",
            "eina chingkhrei",
            "fuckni",
            "pakhon",
            "nangna ee",
            "matung pangbagi",
            "tok oirammi",
            "pukning leirammi",
            "eitaba",
            "heiba",
            "khaangba",
            "chingpuroi",
            "nangna hanjinba",
            "sanu nupa",
            "matam mangba",
            "mamai chatpa",
            "khudol oiraba",
            "kattha",
            "eemai",
            "nupi macha",
            "nangna yeningba",
            "bitchni",
            "moronni",
            "sengba",
            "mairu",
            "eidi khongdana",
            "nangna lairu",
            "thuina",
            "kiching",
            "ꯍꯩꯕꯥꯛ",
            "ꯅꯪꯅ ꯄꯨꯛꯅꯤꯡꯕ",
            "ꯑꯩꯅ ꯆꯤꯡꯈ꯭ꯔꯦꯢ",
            "fuckꯅꯤ",
            "ꯄꯥꯈꯣꯟ",
            "ꯅꯪꯅ ꯑꯤ",
            "ꯃꯇꯨꯡ ꯄꯥꯡꯕꯥꯒꯤ",
            "ꯇꯣꯛ ꯑꯣꯢꯔꯝꯃꯤ",
            "ꯄꯨꯛꯅꯤꯡ ꯂꯩꯔꯝꯃꯤ",
            "ꯑꯩꯇꯕ",
            "ꯍꯩꯕ",
            "ꯈꯥꯡꯕ",
            "ꯆꯤꯡꯄꯨꯔꯣꯢ",
            "ꯅꯪꯅ ꯍꯟꯖꯤꯡꯕ",
            "ꯁꯅꯨ ꯅꯨꯄ",
            "ꯃꯇꯝ ꯃꯪꯕ",
            "ꯃꯃꯥꯢ ꯆꯥꯠꯄ",
            "ꯈꯨꯗꯣꯜ ꯑꯣꯢꯔꯕ",
            "ꯀꯇꯥ",
            "ꯑꯤꯃꯥꯢ",
            "ꯅꯨꯄꯤ ꯃꯆ",
            "ꯅꯪꯅ ꯌꯦꯅꯤꯡꯕ",
            "bitchꯅꯤ",
            "moronꯅꯤ",
            "ꯁꯦꯡꯕ",
            "ꯃꯥꯢꯔꯨ",
            "ꯑꯩꯗꯤ ꯈꯣꯡꯗꯅ",
            "ꯅꯪꯅ ꯂꯥꯢꯔꯨ",
            "ꯊꯨꯢꯅ",
            "ꯀꯤꯆꯤꯡ",
        ],
    ],
    [
        "nepali",
        [
            "chikne",
            "khaire",
            "boka",
            "budi",
            "budo",
            "gandu",
            "gand",
            "chikthi",
            "kukur ko chhora",
            "bhand",
            "jatha",
            "jathi",
            "chodnu",
            "choday",
            "randika",
            "randipana",
            "bhag sala",
            "madarchod",
            "behenchod",
            "kutti",
            "kuteko mukh",
            "lauda",
            "lauro",
            "lauroko taato",
            "jatha khane",
            "gandu sala",
            "boka sala",
            "chikeko",
            "pesa garne",
            "thoppa",
            "randi",
            "haramzada",
            "dalle",
            "damichor",
            "pote",
            "napunsak",
            "khaleko",
            "khaneko",
            "beshya",
            "kutta",
            "suar ko choro",
            "चिक्ने",
            "खैरे",
            "बोका",
            "बुढी",
            "बुढो",
            "गाण्डु",
            "गाँड",
            "चिक्थी",
            "कुकुरको छोरा",
            "भण्ड",
            "जठा",
            "जाठी",
            "चोद्नु",
            "चोडे",
            "रन्डीका",
            "रन्डीपना",
            "भाग साला",
            "मादरचोद",
            "बहनचोद",
            "कुट्टी",
            "कुटेको मुख",
            "लौडा",
            "लौरो",
            "लौरोको तातो",
            "जठा खाने",
            "गाण्डु साला",
            "बोका साला",
            "चिकेको",
            "पेसा गर्ने",
            "थोप्पा",
            "रन्डी",
            "हरामजादा",
            "डल्ले",
            "डामीचोर",
            "पोटे",
            "नपुंसक",
            "खालेको",
            "खानेको",
            "बेश्या",
            "कुत्ता",
            "सुँगुरको छोरा",
        ],
    ],
    [
        "odia",
        [
            "randika",
            "randi",
            "kundi",
            "gandu",
            "launda",
            "laundi",
            "chikna",
            "chikni",
            "mada chod",
            "gand mara",
            "chodiba",
            "chodibu",
            "madarchod",
            "behenchod",
            "kuduchi",
            "chutia",
            "pagala",
            "gand",
            "boka",
            "suar",
            "kutiya",
            "randipanira",
            "launda sala",
            "kutti",
            "gandukhia",
            "thenga deba",
            "mu chudibi",
            "mu randi",
            "tate khai deibi",
            "launda ku",
            "laundira",
            "suar ku",
            "dohari",
            "nalaia",
            "khoja",
            "kanduka",
            "gandila",
            "kundi mariba",
            "mo bapa",
            "tate jharichi",
            "tate chudibi",
            "khaibe tu gand",
            "ରଣ୍ଡିକା",
            "ରଣ୍ଡି",
            "କୁଣ୍ଡି",
            "ଗାଣ୍ଡୁ",
            "ଲଉଣ୍ଡା",
            "ଲଉଣ୍ଡି",
            "ଚିକ୍ନା",
            "ଚିକ୍ନି",
            "ମାଦ ଚୋଦ",
            "ଗାଣ୍ଡ ମାର",
            "ଚୋଦିବ",
            "ଚୋଦିବୁ",
            "ମାଦରଚୋଦ",
            "ବେହେନଚୋଦ",
            "କୁଡୁଚି",
            "ଚୁତିଆ",
            "ପାଗଳ",
            "ଗାଣ୍ଡ",
            "ବୋକା",
            "ଶୁଅର",
            "କୁଟିୟା",
            "ରଣ୍ଡିପଣୀରା",
            "ଲଉଣ୍ଡା ସାଲା",
            "କୁଟି",
            "ଗାଣ୍ଡୁଖିଆ",
            "ଠେଙ୍ଗା ଦେବା",
            "ମୁଁ ଚୁଡିବି",
            "ମୁଁ ରଣ୍ଡି",
            "ତତେ ଖାଇ ଦେଇବି",
            "ଲଉଣ୍ଡାକୁ",
            "ଲଉଣ୍ଡିରା",
            "ଶୁଅରକୁ",
            "ଡହାରି",
            "ନଳାଇଆ",
            "ଖୋଜା",
            "କନ୍ଦୁକା",
            "ଗାଣ୍ଡିଲା",
            "କୁଣ୍ଡି ମାରିବ",
            "ମୋ ବାପା",
            "ତତେ ଝାରିଛି",
            "ତତେ ଚୁଡିବି",
            "ଖାଇବେ ତୁ ଗାଣ୍ଡ",
        ],
    ],
    [
        "punjabi",
        [
            "chut",
            "chutiyapa",
            "chutiyapanti",
            "chutiyapan",
            "chod",
            "chodai",
            "chodna",
            "chodne",
            "chodne wala",
            "chodne wali",
            "madarchod",
            "madarchodi",
            "madarchodiyan",
            "madarchodiyon",
            "bhosdiwala",
            "bhosdiwali",
            "bhosdiwale",
            "bhosdike",
            "bhosdikiya",
            "bhosdiyon",
            "gaanduu",
            "bhosdi",
            "chudwa",
            "behanchod",
            "land",
            "lavda",
            "napunsak",
            "harami",
            "haramkhor",
            "randi",
            "rand",
            "chutiya",
            "jhaant",
            "gaandphatli",
            "gand",
            "gandu",
            "chutia",
            "bhenchod",
            "kamini",
            "kamine",
            "chodu",
            "chodde",
            "jhant",
            "jhantoo",
            "chikna",
            "chikni",
            "kutti",
            "kutte da pilla",
            "haraami",
            "gandu sala",
            "tera baap",
            "teri maa di",
            "teri behan di",
            "lund",
            "launda",
            "laundi",
            "jhatu",
            "chodiyan",
            "gand marna",
            "chikne",
            "rundi",
            "kutta",
            "gandu da baccha",
            "chinal",
            "khotey da puttar",
            "saala",
            "haraamzada",
            "bhen di lodi",
            "maa di chut",
            "behn di chut",
            "teri maa di chut",
            "ਗਾਂਡ",
            "ਗਾਂਡੂ",
            "ਚੂਤੀਆ",
            "ਭੈਣਚੋਦ",
            "ਮਾਦਰਚੋਦ",
            "ਰੰਡੀ",
            "ਕਾਮੀਨੀ",
            "ਕਾਮੀਨੇ",
            "ਭੋਸਡੀ",
            "ਭੋਸਡੀਕੇ",
            "ਚੋਦ",
            "ਚੋਦੂ",
            "ਚੋਦਣਾ",
            "ਚੋੱਦੇ",
            "ਝਾਂਟ",
            "ਝਾਂਟੂ",
            "ਚਿਕਣਾ",
            "ਚਿਕਣੀ",
            "ਕੁੱਤੀ",
            "ਕੁੱਤੇ ਦਾ ਪਿੱਲਾ",
            "ਹਰਾਮੀ",
            "ਗਾਂਡੂ ਸਾਲਾ",
            "ਤੇਰਾ ਬਾਪ",
            "ਤੇਰੀ ਮਾਂ ਦੀ",
            "ਤੇਰੀ ਭੈਣ ਦੀ",
            "ਲੁੰਡ",
            "ਲੌਂਡਾ",
            "ਲੌਂਡੀ",
            "ਝਟੂ",
            "ਚੋਦੀਆਂ",
            "ਗਾਂਡ ਮਾਰਣਾ",
            "ਚਿਕਨੇ",
            "ਰੁੰਡੀ",
            "ਕੁੱਤਾ",
            "ਗਾਂਡੂ ਦਾ ਬੱਚਾ",
            "ਛਿਨਾਲ",
            "ਖੋਟੇ ਦਾ ਪੁੱਤਰ",
            "ਸਾਲਾ",
            "ਹਰਾਮਜ਼ਾਦਾ",
            "ਭੈਣ ਦੀ ਲੋੜੀ",
            "ਮਾਂ ਦੀ ਚੂਤ",
            "ਭੈਣ ਦੀ ਚੂਤ",
            "ਤੇਰੀ ਮਾਂ ਦੀ ਚੂਤ",
        ],
    ],
    [
        "tamil",
        [
            "punda",
            "pundai",
            "pundaati",
            "sombu",
            "sombu mandaya",
            "thevdiya",
            "thevdiya payal",
            "thevidiya",
            "thevidiya magan",
            "thevidiya paiya",
            "saniyan",
            "sani kudhira",
            "soothu",
            "sappa figure",
            "kundi",
            "sattai",
            "nayyandi",
            "nayyadi",
            "gathi illatha",
            "kandupidikka mudiyala",
            "muttaala",
            "mandaya",
            "kevalam",
            "kevalamana paiyan",
            "onnume puriyala",
            "seiyarathu enna",
            "thala vazhi",
            "sani thooral",
            "vittu",
            "vittu vettu",
            "po da",
            "po di",
            "venda",
            "sethuru",
            "aapu",
            "pundaikku aapu",
            "soodu",
            "moona veli",
            "enna da dei",
            "mokka",
            "mokkai",
            "saavu graaki",
            "munda",
            "seththu poi",
            "mandaya pichu",
            "edhiri",
            "thukali",
            "arai en 5",
            "kudunga mairu",
            "புண்ட",
            "புண்டை",
            "புண்டாட்டி",
            "சோம்பு",
            "சோம்பு மண்டைய",
            "தேவடியா",
            "தேவடியா பயல்",
            "தேவிடியா",
            "தேவிடியா மகன்",
            "தேவிடியா பைய",
            "சாணியன்",
            "சாணி குதிர",
            "சூத்து",
            "சப்பா ஃபிகர்",
            "குண்டி",
            "சட்டை",
            "நையாண்டி",
            "நையாடி",
            "கதி இல்லாத",
            "கண்டுபிடிக்க முடியல",
            "முட்டாள",
            "மண்டைய",
            "கேவலம்",
            "கேவலமான பையன்",
            "ஒன்னும் புரியல",
            "செய்யரது என்ன",
            "தலை வழி",
            "சாணி தூறல்",
            "விட்டு",
            "விட்டு வெட்டு",
            "போ டா",
            "போ டி",
            "வேண்டா",
            "செத்துறு",
            "ஆப்பு",
            "புண்டைக்கு ஆப்பு",
            "சூடு",
            "மூணா வெளி",
            "என்ன டா டெய்",
            "மொக்கா",
            "மொக்கை",
            "சாவு கிராக்கி",
            "முண்ட",
            "செத்து போயி",
            "மண்டைய பிச்சு",
            "எதிரி",
            "தூகலி",
            "அரை என் ஐந்து",
            "குடுங்க மைறு",
        ],
    ],
    [
        "telugu",
        [
            "dengudu",
            "denguta",
            "denginchav",
            "dengestha",
            "dengina",
            "lancham",
            "dengina kodaka",
            "guddalo dengu",
            "nee amma dengu",
            "nee talli dengu",
            "puku",
            "pukulo",
            "puku donga",
            "loda",
            "loda kodaka",
            "nee kodaka",
            "kodaka",
            "donga kodaka",
            "chusina kodaka",
            "chusina gadu",
            "donga",
            "sannayi",
            "sannasi",
            "sani kodaka",
            "kukka",
            "cheddi",
            "cheddodu",
            "cheddam",
            "puka",
            "puku pai naaku",
            "puku meeda",
            "jaffa",
            "jaffa gadu",
            "thaadu",
            "gandu",
            "nee puku",
            "dongana kodaka",
            "thokka",
            "thokkanu",
            "lancham kodaka",
            "siggu ledha",
            "nayala kodaka",
            "ammayi chudra",
            "lanjakodaka",
            "దెంగుడు",
            "దెంగుట",
            "దెంగించావ్",
            "దెంగేస్తా",
            "దెంగిన",
            "లంచం",
            "దెంగిన కొడకా",
            "గుద్దలో దెంగు",
            "నీ అమ్మ దెంగు",
            "నీ తల్లి దెంగు",
            "పుకు",
            "పుకులో",
            "పుకు దొంగ",
            "లోడా",
            "లోడా కొడకా",
            "నీ కొడకా",
            "కొడకా",
            "దొంగ కొడకా",
            "చూసిన కొడకా",
            "చూసిన గాడు",
            "దొంగ",
            "సన్నాయి",
            "సన్నాసి",
            "సాని కొడకా",
            "కుక్క",
            "చెడ్డి",
            "చెడ్డోడు",
            "చెడ్డం",
            "పుకా",
            "పుకు పై నాకు",
            "పుకు మీద",
            "జాఫ్ఫా",
            "జాఫ్ఫా గాడు",
            "తాడు",
            "గాండు",
            "నీ పుకు",
            "దొంగన కొడకా",
            "తొక్క",
            "తొక్కాను",
            "లంచం కొడకా",
            "సిగ్గు లేదా",
            "నాయల కొడకా",
            "అమ్మాయి చూద్రా",
            "లంజకొడకా",
        ],
    ],
    [
        "urdu",
        [
            "chutiya",
            "chutiyapa",
            "bhenchod",
            "behnchod",
            "madarchod",
            "maa chod",
            "lodu",
            "loda",
            "lund",
            "gaand",
            "gandu",
            "gaand mara",
            "randi",
            "randi khana",
            "haraami",
            "haramzada",
            "haramzadi",
            "chuswa",
            "chusne wala",
            "chod",
            "choda",
            "chudi",
            "chudai",
            "sali",
            "saala",
            "kutta",
            "kutti",
            "gand mara",
            "lund chus",
            "chus le",
            "bhen ke lode",
            "maa ke lode",
            "madar ke lode",
            "teri maa ki",
            "teri behen ki",
            "teri gand",
            "tera lund",
            "bosri",
            "bosdike",
            "lafanga",
            "bhosri",
            "bhosdike",
            "chut",
            "patak ke rakh dunga",
            "gaand faad dunga",
            "kamina",
            "kameeni",
            "raand",
            "kutta kamina",
            "harami ka bacha",
            "kutiya",
            "kuttay ki aulad",
            "teri maa ka bhosda",
            "beghairat",
            "najaayaz",
            "چوتیا",
            "چوتیاپا",
            "بہن چود",
            "مادرچود",
            "ماں چود",
            "لوڑا",
            "لنڈ",
            "گانڈ",
            "گاندو",
            "گاند مارا",
            "رنڈی",
            "رنڈی خانہ",
            "حرامی",
            "حرام زادہ",
            "حرام زادی",
            "چسوا",
            "چوسنے والا",
            "چود",
            "چودا",
            "چدی",
            "چدائی",
            "سالی",
            "سالا",
            "کتا",
            "کٹی",
            "گاند مار",
            "لنڈ چوس",
            "چوس لے",
            "بہن کے لوڑے",
            "ماں کے لوڑے",
            "مادر کے لوڑے",
            "تیری ماں کی",
            "تیری بہن کی",
            "تیری گانڈ",
            "تیرا لنڈ",
            "بوسڑی",
            "بوسڈیکے",
            "لفنگا",
            "بھوسڑی",
            "بھوسڈیکے",
            "چوت",
            "پٹک کے رکھ دوں گا",
            "گانڈ پھاڑ دوں گا",
            "کمینہ",
            "کمینی",
            "راند",
            "کتا کمینہ",
            "حرامی کا بچہ",
            "کتیا",
            "کتے کی اولاد",
            "تیری ماں کا بھوسڑا",
            "بےغیرت",
            "ناجائز",
        ],
    ],
    [
        "haryanvi",
        [
            "chutmar",
            "lund",
            "gand",
            "bhosdike",
            "madarchod",
            "behnchod",
            "randi",
            "chutiya",
            "chod",
            "gaandfat",
            "chodunga",
            "chudwa",
            "lauda",
            "laude ka",
            "laude ki baat",
            "randi ke bacche",
            "kutte",
            "kamine",
            "bawli tared",
            "bawli boocho",
            "bawli gand",
            "gandu",
            "gaand mara",
            "chut ke bal",
            "chup madarchod",
            "teri maa ki chut",
            "jhaat ke baal",
            "chod ke aaya",
            "lulli",
            "lund le",
            "teri maa chod",
            "teri behen chod",
            "gaandu",
            "gaand mein le",
            "randi rona",
            "lodu",
            "tharki",
            "khoteya",
            "haraami",
            "ullu ke pathe",
            "bhosdi ke",
            "bhosdiwale",
            "madar ke lode",
            "chusle",
            "chuswa",
            "tharki buddha",
            "kamina",
            "kutti",
            "kutiya",
            "chudail",
            "raand",
            "choos le",
            "bakchod",
            "bakchodi",
            "tatte",
            "tatti",
            "bhadwe",
            "ghatiya",
            "gandi aulaad",
            "चुतमार",
            "लंड",
            "गांड",
            "भोसडीके",
            "मादरचोद",
            "बहनचोद",
            "रंडी",
            "चूतिया",
            "चोद",
            "गांडफट",
            "चोदूंगा",
            "चुदवा",
            "लौड़ा",
            "लौड़े का",
            "लौड़े की बात",
            "रंडी के बच्चे",
            "कुत्ते",
            "कमीन",
            "बावली तरेड़",
            "बावली बूचो",
            "बावली गांड",
            "गांडू",
            "गांड मारा",
            "चूत के बाल",
            "चुप मादरचोद",
            "तेरी माँ की चूत",
            "झाट के बाल",
            "चोद के आया",
            "लुल्ली",
            "लंड ले",
            "तेरी माँ चोद",
            "तेरी बहन चोद",
            "गांड में ले",
            "रंडी रोना",
            "लोडू",
            "ठरकी",
            "खोटेया",
            "हरामी",
            "उल्लू के पठे",
            "भोसड़ी के",
            "भोसड़ीवाले",
            "मादर के लंड",
            "चूसले",
            "चुसवा",
            "ठरकी बूढ़ा",
            "कमीना",
            "कुट्टी",
            "कुतिया",
            "चुड़ैल",
            "रांड",
            "चूस ले",
            "बकचोद",
            "बकचोदी",
            "टट्टे",
            "टट्टी",
            "भड़वे",
            "घटिया",
            "गंदी औलाद",
        ],
    ],
    [
        "marwari",
        [
            "chudiyo",
            "chodiyo",
            "laude ro",
            "randi ro chokro",
            "lauda",
            "laudo",
            "gandfat",
            "bawli chudel",
            "bawli boocho",
            "maderchod",
            "behnchod",
            "maa chod",
            "gandu",
            "tharki gandu",
            "thobda tod dunga",
            "kharoch",
            "choos le",
            "bhosdike thare",
            "bakchod",
            "bakchodi",
            "chutmar",
            "randi",
            "kutti",
            "kutiya",
            "raand",
            "gaandu",
            "gand mara",
            "lauda le",
            "gaand phad dunga",
            "nalla",
            "tharki",
            "bhosri",
            "चुडियो",
            "चोदियो",
            "लौड़े रो",
            "रंडी रो छोकरो",
            "लौड़ा",
            "लौड़ो",
            "गांडफट",
            "बावली चुड़ैल",
            "बावली बूचो",
            "मादरचोद",
            "बहनचोद",
            "माँ चोद",
            "गांडू",
            "ठरकी गांडू",
            "थोबड़ा तोड़ दूंगा",
            "खरोंच",
            "चूस ले",
            "भोसडीके थारे",
            "बकचोद",
            "बकचोदी",
            "चुतमार",
            "रंडी",
            "कुत्ती",
            "कुतिया",
            "रांड",
            "गांड मारा",
            "लौड़ा ले",
            "गांड फाड़ दूंगा",
            "नल्ला",
            "ठरकी",
            "भोसड़ी",
        ],
    ],
    [
        "rajasthani",
        [
            "chootiya",
            "chodu",
            "gand mara",
            "madarchod",
            "behnchod",
            "jhaatu",
            "tharki",
            "bhosdike",
            "ullu ke pathe",
            "kamina",
            "bakchod",
            "chikna",
            "kutti",
            "gandu",
            "kamine",
            "beghairat",
            "bhosdiwale",
            "loda",
            "lund",
            "choosne wala",
            "tharki buddha",
            "चूतिया",
            "चोदू",
            "गांड मारा",
            "मादरचोद",
            "बहनचोद",
            "झाटू",
            "ठरकी",
            "भोसडीके",
            "उल्लू के पट्ठे",
            "कमीना",
            "बकचोद",
            "चिकना",
            "कुत्ती",
            "गांडू",
            "कमीने",
            "बेगैरत",
            "भोसड़ीवाले",
            "लौड़ा",
            "लंड",
            "चूसने वाला",
            "ठरकी बूढ़ा",
        ],
    ],
]);

module.exports = wordsMap;

// let total = 0;
// for (const arr of wordsMap.values()) {
//     total += arr.length;
// }
// console.log("Total slang words:", total);